#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MainMenu_Technology_Content

#include "Basic.hpp"

#include "WBP_MainMenu_Technology_Content_classes.hpp"
#include "WBP_MainMenu_Technology_Content_parameters.hpp"


namespace SDK
{

// Function WBP_MainMenu_Technology_Content.WBP_MainMenu_Technology_Content_C.AnmEvent_Focus
// (BlueprintCallable, BlueprintEvent)

void UWBP_MainMenu_Technology_Content_C::AnmEvent_Focus()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenu_Technology_Content_C", "AnmEvent_Focus");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenu_Technology_Content.WBP_MainMenu_Technology_Content_C.AnmEvent_Unfocus
// (BlueprintCallable, BlueprintEvent)

void UWBP_MainMenu_Technology_Content_C::AnmEvent_Unfocus()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenu_Technology_Content_C", "AnmEvent_Unfocus");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenu_Technology_Content.WBP_MainMenu_Technology_Content_C.AnmEvent_Unlock
// (BlueprintCallable, BlueprintEvent)

void UWBP_MainMenu_Technology_Content_C::AnmEvent_Unlock()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenu_Technology_Content_C", "AnmEvent_Unlock");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenu_Technology_Content.WBP_MainMenu_Technology_Content_C.AnmEvent_UpdateDetail
// (BlueprintCallable, BlueprintEvent)

void UWBP_MainMenu_Technology_Content_C::AnmEvent_UpdateDetail()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenu_Technology_Content_C", "AnmEvent_UpdateDetail");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenu_Technology_Content.WBP_MainMenu_Technology_Content_C.BndEvt__WBP_MainMenu_Technology_Content_WBP_PalInvisibleButton_K2Node_ComponentBoundEvent_3_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_MainMenu_Technology_Content_C::BndEvt__WBP_MainMenu_Technology_Content_WBP_PalInvisibleButton_K2Node_ComponentBoundEvent_3_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenu_Technology_Content_C", "BndEvt__WBP_MainMenu_Technology_Content_WBP_PalInvisibleButton_K2Node_ComponentBoundEvent_3_CommonButtonBaseClicked__DelegateSignature");

	Params::WBP_MainMenu_Technology_Content_C_BndEvt__WBP_MainMenu_Technology_Content_WBP_PalInvisibleButton_K2Node_ComponentBoundEvent_3_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_MainMenu_Technology_Content.WBP_MainMenu_Technology_Content_C.BndEvt__WBP_MainMenu_Technology_Content_WBP_PalInvisibleButton_K2Node_ComponentBoundEvent_4_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_MainMenu_Technology_Content_C::BndEvt__WBP_MainMenu_Technology_Content_WBP_PalInvisibleButton_K2Node_ComponentBoundEvent_4_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenu_Technology_Content_C", "BndEvt__WBP_MainMenu_Technology_Content_WBP_PalInvisibleButton_K2Node_ComponentBoundEvent_4_CommonButtonBaseClicked__DelegateSignature");

	Params::WBP_MainMenu_Technology_Content_C_BndEvt__WBP_MainMenu_Technology_Content_WBP_PalInvisibleButton_K2Node_ComponentBoundEvent_4_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_MainMenu_Technology_Content.WBP_MainMenu_Technology_Content_C.BndEvt__WBP_MainMenu_Technology_Content_WBP_PalInvisibleButton_K2Node_ComponentBoundEvent_5_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_MainMenu_Technology_Content_C::BndEvt__WBP_MainMenu_Technology_Content_WBP_PalInvisibleButton_K2Node_ComponentBoundEvent_5_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenu_Technology_Content_C", "BndEvt__WBP_MainMenu_Technology_Content_WBP_PalInvisibleButton_K2Node_ComponentBoundEvent_5_CommonButtonBaseClicked__DelegateSignature");

	Params::WBP_MainMenu_Technology_Content_C_BndEvt__WBP_MainMenu_Technology_Content_WBP_PalInvisibleButton_K2Node_ComponentBoundEvent_5_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_MainMenu_Technology_Content.WBP_MainMenu_Technology_Content_C.ExecuteUbergraph_WBP_MainMenu_Technology_Content
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_MainMenu_Technology_Content_C::ExecuteUbergraph_WBP_MainMenu_Technology_Content(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenu_Technology_Content_C", "ExecuteUbergraph_WBP_MainMenu_Technology_Content");

	Params::WBP_MainMenu_Technology_Content_C_ExecuteUbergraph_WBP_MainMenu_Technology_Content Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_MainMenu_Technology_Content.WBP_MainMenu_Technology_Content_C.GetBindedTechnologyName
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FName                             TechnologyName                                         (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_MainMenu_Technology_Content_C::GetBindedTechnologyName(class FName* TechnologyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenu_Technology_Content_C", "GetBindedTechnologyName");

	Params::WBP_MainMenu_Technology_Content_C_GetBindedTechnologyName Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (TechnologyName != nullptr)
		*TechnologyName = Parms.TechnologyName;
}


// Function WBP_MainMenu_Technology_Content.WBP_MainMenu_Technology_Content_C.isUnlockable
// (Private, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool                                    Param_IsUnlockable                                     (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_MainMenu_Technology_Content_C::IsUnlockable(bool* Param_IsUnlockable)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenu_Technology_Content_C", "isUnlockable");

	Params::WBP_MainMenu_Technology_Content_C_IsUnlockable Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Param_IsUnlockable != nullptr)
		*Param_IsUnlockable = Parms.Param_IsUnlockable;
}


// Function WBP_MainMenu_Technology_Content.WBP_MainMenu_Technology_Content_C.IsUnlocked
// (Private, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool                                    Param_IsUnlocked                                       (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_MainMenu_Technology_Content_C::IsUnlocked(bool* Param_IsUnlocked)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenu_Technology_Content_C", "IsUnlocked");

	Params::WBP_MainMenu_Technology_Content_C_IsUnlocked Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Param_IsUnlocked != nullptr)
		*Param_IsUnlocked = Parms.Param_IsUnlocked;
}


// Function WBP_MainMenu_Technology_Content.WBP_MainMenu_Technology_Content_C.OnClickedButton__DelegateSignature
// (Public, Delegate, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWBP_MainMenu_Technology_Content_C*Widget                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_MainMenu_Technology_Content_C::OnClickedButton__DelegateSignature(class UWBP_MainMenu_Technology_Content_C* Widget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenu_Technology_Content_C", "OnClickedButton__DelegateSignature");

	Params::WBP_MainMenu_Technology_Content_C_OnClickedButton__DelegateSignature Parms{};

	Parms.Widget = Widget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_MainMenu_Technology_Content.WBP_MainMenu_Technology_Content_C.OnHovered_Internal
// (Private, BlueprintCallable, BlueprintEvent)

void UWBP_MainMenu_Technology_Content_C::OnHovered_Internal()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenu_Technology_Content_C", "OnHovered_Internal");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenu_Technology_Content.WBP_MainMenu_Technology_Content_C.OnHoveredButton__DelegateSignature
// (Public, Delegate, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWBP_MainMenu_Technology_Content_C*Widget                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_MainMenu_Technology_Content_C::OnHoveredButton__DelegateSignature(class UWBP_MainMenu_Technology_Content_C* Widget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenu_Technology_Content_C", "OnHoveredButton__DelegateSignature");

	Params::WBP_MainMenu_Technology_Content_C_OnHoveredButton__DelegateSignature Parms{};

	Parms.Widget = Widget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_MainMenu_Technology_Content.WBP_MainMenu_Technology_Content_C.OnInitialized
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_MainMenu_Technology_Content_C::OnInitialized()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenu_Technology_Content_C", "OnInitialized");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenu_Technology_Content.WBP_MainMenu_Technology_Content_C.OnUnhovered_Internal
// (Private, BlueprintCallable, BlueprintEvent)

void UWBP_MainMenu_Technology_Content_C::OnUnhovered_Internal()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenu_Technology_Content_C", "OnUnhovered_Internal");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MainMenu_Technology_Content.WBP_MainMenu_Technology_Content_C.OnUnhoveredButton__DelegateSignature
// (Public, Delegate, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWBP_MainMenu_Technology_Content_C*Widget                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_MainMenu_Technology_Content_C::OnUnhoveredButton__DelegateSignature(class UWBP_MainMenu_Technology_Content_C* Widget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenu_Technology_Content_C", "OnUnhoveredButton__DelegateSignature");

	Params::WBP_MainMenu_Technology_Content_C_OnUnhoveredButton__DelegateSignature Parms{};

	Parms.Widget = Widget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_MainMenu_Technology_Content.WBP_MainMenu_Technology_Content_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_MainMenu_Technology_Content_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenu_Technology_Content_C", "PreConstruct");

	Params::WBP_MainMenu_Technology_Content_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_MainMenu_Technology_Content.WBP_MainMenu_Technology_Content_C.SetShouldMaskSkillUnlock
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<class FName>                     ItemRecipes                                            (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UWBP_MainMenu_Technology_Content_C::SetShouldMaskSkillUnlock(TArray<class FName>& ItemRecipes)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenu_Technology_Content_C", "SetShouldMaskSkillUnlock");

	Params::WBP_MainMenu_Technology_Content_C_SetShouldMaskSkillUnlock Parms{};

	Parms.ItemRecipes = std::move(ItemRecipes);

	UObject::ProcessEvent(Func, &Parms);

	ItemRecipes = std::move(Parms.ItemRecipes);
}


// Function WBP_MainMenu_Technology_Content.WBP_MainMenu_Technology_Content_C.Setup
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             TechnologyName                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_MainMenu_Technology_Content_C::Setup(class FName TechnologyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenu_Technology_Content_C", "Setup");

	Params::WBP_MainMenu_Technology_Content_C_Setup Parms{};

	Parms.TechnologyName = TechnologyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_MainMenu_Technology_Content.WBP_MainMenu_Technology_Content_C.UpdateButtonDetail
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWBP_MainMenu_Technology_Content_C::UpdateButtonDetail()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MainMenu_Technology_Content_C", "UpdateButtonDetail");

	UObject::ProcessEvent(Func, nullptr);
}

}

