#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_PalWorkPowerPlant_Gauge

#include "Basic.hpp"

#include "WBP_PalWorkPowerPlant_Gauge_classes.hpp"
#include "WBP_PalWorkPowerPlant_Gauge_parameters.hpp"


namespace SDK
{

// Function WBP_PalWorkPowerPlant_Gauge.WBP_PalWorkPowerPlant_Gauge_C.AnmEvent_Changing
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsChanging                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_PalWorkPowerPlant_Gauge_C::AnmEvent_Changing(bool IsChanging)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PalWorkPowerPlant_Gauge_C", "AnmEvent_Changing");

	Params::WBP_PalWorkPowerPlant_Gauge_C_AnmEvent_Changing Parms{};

	Parms.IsChanging = IsChanging;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_PalWorkPowerPlant_Gauge.WBP_PalWorkPowerPlant_Gauge_C.ExecuteUbergraph_WBP_PalWorkPowerPlant_Gauge
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_PalWorkPowerPlant_Gauge_C::ExecuteUbergraph_WBP_PalWorkPowerPlant_Gauge(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PalWorkPowerPlant_Gauge_C", "ExecuteUbergraph_WBP_PalWorkPowerPlant_Gauge");

	Params::WBP_PalWorkPowerPlant_Gauge_C_ExecuteUbergraph_WBP_PalWorkPowerPlant_Gauge Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_PalWorkPowerPlant_Gauge.WBP_PalWorkPowerPlant_Gauge_C.SetState
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsLow                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    Show                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_PalWorkPowerPlant_Gauge_C::SetState(bool IsLow, bool Show)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PalWorkPowerPlant_Gauge_C", "SetState");

	Params::WBP_PalWorkPowerPlant_Gauge_C_SetState Parms{};

	Parms.IsLow = IsLow;
	Parms.Show = Show;

	UObject::ProcessEvent(Func, &Parms);
}

}

