#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MenuESC

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "SlateCore_structs.hpp"
#include "Pal_structs.hpp"
#include "Pal_classes.hpp"
#include "E_PalEscMenuType_structs.hpp"
#include "UMG_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_MenuESC.WBP_MenuESC_C
// 0x0420 (0x0850 - 0x0430)
class UWBP_MenuESC_C final : public UPalUserWidgetOverlayUI
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0430(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       Anm_Clipboard_InToOut;                             // 0x0438(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Anm_Copy_NormalToFocus;                            // 0x0440(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UCheckBox*                              AimAssistKeyboard_CheckBox;                        // 0x0448(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCheckBox*                              AimAssistPad_CheckBox;                             // 0x0450(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCheckBox*                              bActiveUNKO_CheckBox;                              // 0x0458(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCheckBox*                              bEnableFriendlyFire_CheckBox;                      // 0x0460(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCheckBox*                              bEnableInvaderEnemy_CheckBox;                      // 0x0468(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBP_PalRichTextBlock_C*                 BP_PalRichTextBlock_MultiTips;                     // 0x0470(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBP_PalTextBlock_C*                     BPPalTextBlock_JitterNum;                          // 0x0478(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBP_PalTextBlock_C*                     BPPalTextBlock_JoinNum;                            // 0x0480(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBP_PalTextBlock_C*                     BPPalTextBlock_PacketlossNum;                      // 0x0488(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBP_PalTextBlock_C*                     BPPalTextBlock_RTTNum;                             // 0x0490(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBP_PalTextBlock_C*                     BPPalTextBlock_ServerFPSNum;                       // 0x0498(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBP_PalTextBlock_C*                     BPPalTextBlock_WorldExplain;                       // 0x04A0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBP_PalTextBlock_C*                     BPPalTextBlock_WorldName;                          // 0x04A8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USpinBox*                               BuildObjectDamageRate_SpinBox;                     // 0x04B0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCanvasPanel*                           Canvas_Buttons;                                    // 0x04B8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCanvasPanel*                           CanvasPanel_MultiTips;                             // 0x04C0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USpinBox*                               CollectionDropRate_SpinBox;                        // 0x04C8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USpinBox*                               CollectionObjectHpRate_SpinBox;                    // 0x04D0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USpinBox*                               CollectionObjectRespawnSpeedRate;                  // 0x04D8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USpinBox*                               DayTimeSpeedRateValue_SpinBox;                     // 0x04E0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UComboBoxString*                        DeathPenalty_ComboBox;                             // 0x04E8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UComboBoxString*                        Difficulty_ComboBox;                               // 0x04F0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USpinBox*                               DropItemMaxNum_SpinBox;                            // 0x04F8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USpinBox*                               DropItemMaxNum_UNKO_SpinBox;                       // 0x0500(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USpinBox*                               EnemyDropItemRate_SpinBox;                         // 0x0508(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USpinBox*                               ExpRate_SpinBox;                                   // 0x0510(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHorizontalBox*                         HorizontalBox_Jitter;                              // 0x0518(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHorizontalBox*                         HorizontalBox_JoinNum;                             // 0x0520(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHorizontalBox*                         HorizontalBox_PacketLoss;                          // 0x0528(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHorizontalBox*                         HorizontalBox_RTT;                                 // 0x0530(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHorizontalBox*                         HorizontalBox_ServerFPS;                           // 0x0538(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 IconShowHide;                                      // 0x0540(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_115;                                         // 0x0548(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_CautionBase;                                 // 0x0550(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHorizontalBox*                         InviteCode_HorizontalBox;                          // 0x0558(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USpinBox*                               NightTimeSpeedRate_SpinBox;                        // 0x0560(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UOverlay*                               Overlay_WorldExplain;                              // 0x0568(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USpinBox*                               PalAutoHPRegeneRate_SpinBox;                       // 0x0570(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USpinBox*                               PalAutoHpRegeneRateInSleep_SpinBOx;                // 0x0578(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USpinBox*                               PalCaptureRateAdd_SpinBox;                         // 0x0580(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USpinBox*                               PalDamageRateAttack_SpinBox;                       // 0x0588(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USpinBox*                               PalDamageRateDefense_SpinBox;                      // 0x0590(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USpinBox*                               PalSpawnNumRate_SpinBox;                           // 0x0598(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USpinBox*                               PalStaminaDecreaceRate;                            // 0x05A0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USpinBox*                               PalStomachDecreaceRate_SpinBox;                    // 0x05A8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USpinBox*                               PlayerAutoHPRegeneRate_SpinBox;                    // 0x05B0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USpinBox*                               PlayerAutoHpRegeneRateInSleep_SpinBox;             // 0x05B8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USpinBox*                               PlayerDamageRateAttack_SpinBox;                    // 0x05C0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USpinBox*                               PlayerDamageRateDefense_SpinBox;                   // 0x05C8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USpinBox*                               PlayerStaminaDecreaceRate;                         // 0x05D0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USpinBox*                               PlayerStomachDecreaceRate_SpinBox;                 // 0x05D8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBP_PalTextBlock_C*                     Text_InviteCode;                                   // 0x05E0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVerticalBox*                           VerticalBox_ServerInfo;                            // 0x05E8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVerticalBox*                           VerticalBoxWorld;                                  // 0x05F0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_MenuESC_Button_C*                  WBP_MenuESC_Button;                                // 0x05F8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_MenuESC_Button_C*                  WBP_MenuESC_Button_1;                              // 0x0600(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_MenuESC_Button_C*                  WBP_MenuESC_Button_2;                              // 0x0608(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_MenuESC_Button_C*                  WBP_MenuESC_Button_3;                              // 0x0610(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_MenuESC_Button_C*                  WBP_MenuESC_Button_4;                              // 0x0618(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_MenuESC_Button_C*                  WBP_MenuESC_Button_5;                              // 0x0620(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_MenuESC_Button_C*                  WBP_MenuESC_Button_6;                              // 0x0628(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_PalCommonScrollList_C*             WBP_PalCommonScrollList_Members;                   // 0x0630(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_PalInvisibleButton_C*              WBP_PalInvisibleButton_CopyCode;                   // 0x0638(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_PalInvisibleButton_C*              WBP_PalInvisibleButton_ShoiwHideInviteCode;        // 0x0640(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCanvasPanel*                           WorldOptionCanvas;                                 // 0x0648(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	struct FPalOptionWorldSettings                OptionWorldSettingsCache;                          // 0x0650(0x0138)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FPalOptionAudioSettings                AudioSettingsCache;                                // 0x0788(0x001C)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)
	struct FPalOptionKeyboardSettings             KeyboardSettingsCache;                             // 0x07A4(0x0014)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)
	struct FPalOptionPadSettings                  PadSettingsCache;                                  // 0x07B8(0x001C)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)
	struct FPalOptionGraphicsSettings             GraphicsSettingsCache;                             // 0x07D4(0x0054)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)
	struct FDataTableRowHandle                    KillDialogMsgId;                                   // 0x0828(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)
	struct FDataTableRowHandle                    ToTitleDialogMsgId;                                // 0x0838(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)
	bool                                          bShowInviteCode;                                   // 0x0848(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ApplyWorldPreset(const class FString& Difficulty);
	void ApplyWorldSettings();
	void BndEvt__WBP_MenuESC_AimAssistKeyboard_CheckBox_K2Node_ComponentBoundEvent_27_OnCheckBoxComponentStateChanged__DelegateSignature(bool bIsChecked);
	void BndEvt__WBP_MenuESC_AimAssistPad_CheckBox_K2Node_ComponentBoundEvent_0_OnCheckBoxComponentStateChanged__DelegateSignature(bool bIsChecked);
	void BndEvt__WBP_MenuESC_bActiveUNKO_CheckBox_K2Node_ComponentBoundEvent_24_OnCheckBoxComponentStateChanged__DelegateSignature(bool bIsChecked);
	void BndEvt__WBP_MenuESC_bEnableFriendlyFire_CheckBox_K2Node_ComponentBoundEvent_51_OnCheckBoxComponentStateChanged__DelegateSignature(bool bIsChecked);
	void BndEvt__WBP_MenuESC_bEnableInvaderEnemy_CheckBox_K2Node_ComponentBoundEvent_55_OnCheckBoxComponentStateChanged__DelegateSignature(bool bIsChecked);
	void BndEvt__WBP_MenuESC_BuildObjectDamageRate_SpinBox_K2Node_ComponentBoundEvent_19_OnSpinBoxValueCommittedEvent__DelegateSignature(float InValue, ETextCommit CommitMethod);
	void BndEvt__WBP_MenuESC_CollectionDropRate_SpinBox_K2Node_ComponentBoundEvent_20_OnSpinBoxValueCommittedEvent__DelegateSignature(float InValue, ETextCommit CommitMethod);
	void BndEvt__WBP_MenuESC_CollectionObjectHpRate_SpinBox_K2Node_ComponentBoundEvent_21_OnSpinBoxValueCommittedEvent__DelegateSignature(float InValue, ETextCommit CommitMethod);
	void BndEvt__WBP_MenuESC_ComboBoxString_153_K2Node_ComponentBoundEvent_2_OnSelectionChangedEvent__DelegateSignature(const class FString& SelectedItem, ESelectInfo SelectionType);
	void BndEvt__WBP_MenuESC_DayTimeSpeedRateValue_SpinBox_K2Node_ComponentBoundEvent_1_OnSpinBoxValueCommittedEvent__DelegateSignature(float InValue, ETextCommit CommitMethod);
	void BndEvt__WBP_MenuESC_DropItemMaxNum_SpinBox_K2Node_ComponentBoundEvent_56_OnSpinBoxValueCommittedEvent__DelegateSignature(float InValue, ETextCommit CommitMethod);
	void BndEvt__WBP_MenuESC_DropItemMaxNum_UNKO_SpinBox_K2Node_ComponentBoundEvent_57_OnSpinBoxValueCommittedEvent__DelegateSignature(float InValue, ETextCommit CommitMethod);
	void BndEvt__WBP_MenuESC_EnemyDropItemRate_SpinBox_K2Node_ComponentBoundEvent_23_OnSpinBoxValueCommittedEvent__DelegateSignature(float InValue, ETextCommit CommitMethod);
	void BndEvt__WBP_MenuESC_ExpRate_SpinBox_K2Node_ComponentBoundEvent_4_OnSpinBoxValueCommittedEvent__DelegateSignature(float InValue, ETextCommit CommitMethod);
	void BndEvt__WBP_MenuESC_NightTimeSpeedRate_SpinBox_K2Node_ComponentBoundEvent_3_OnSpinBoxValueCommittedEvent__DelegateSignature(float InValue, ETextCommit CommitMethod);
	void BndEvt__WBP_MenuESC_PalAutoHPRegeneRate_SpinBox_K2Node_ComponentBoundEvent_17_OnSpinBoxValueCommittedEvent__DelegateSignature(float InValue, ETextCommit CommitMethod);
	void BndEvt__WBP_MenuESC_PalAutoHpRegenRateInSleep_SpinBOx_K2Node_ComponentBoundEvent_18_OnSpinBoxValueCommittedEvent__DelegateSignature(float InValue, ETextCommit CommitMethod);
	void BndEvt__WBP_MenuESC_PalCaptureRateAdd_SpinBox_K2Node_ComponentBoundEvent_5_OnSpinBoxValueCommittedEvent__DelegateSignature(float InValue, ETextCommit CommitMethod);
	void BndEvt__WBP_MenuESC_PalDamageRateAttack_SpinBox_K2Node_ComponentBoundEvent_7_OnSpinBoxValueCommittedEvent__DelegateSignature(float InValue, ETextCommit CommitMethod);
	void BndEvt__WBP_MenuESC_PalDamageRateDefense_SpinBox_K2Node_ComponentBoundEvent_8_OnSpinBoxValueCommittedEvent__DelegateSignature(float InValue, ETextCommit CommitMethod);
	void BndEvt__WBP_MenuESC_PalStomachDecreaceRate_SpinBox_K2Node_ComponentBoundEvent_15_OnSpinBoxValueCommittedEvent__DelegateSignature(float InValue, ETextCommit CommitMethod);
	void BndEvt__WBP_MenuESC_PlayerAutoHPRegeneRate_SpinBox_K2Node_ComponentBoundEvent_13_OnSpinBoxValueCommittedEvent__DelegateSignature(float InValue, ETextCommit CommitMethod);
	void BndEvt__WBP_MenuESC_PlayerAutoHpRegenRateInSleep_SpinBox_K2Node_ComponentBoundEvent_14_OnSpinBoxValueCommittedEvent__DelegateSignature(float InValue, ETextCommit CommitMethod);
	void BndEvt__WBP_MenuESC_PlayerDamageRateAttack_SpinBox_K2Node_ComponentBoundEvent_9_OnSpinBoxValueCommittedEvent__DelegateSignature(float InValue, ETextCommit CommitMethod);
	void BndEvt__WBP_MenuESC_PlayerDamageRateDefense_SpinBox_K2Node_ComponentBoundEvent_10_OnSpinBoxValueCommittedEvent__DelegateSignature(float InValue, ETextCommit CommitMethod);
	void BndEvt__WBP_MenuESC_PlayerStomachDecreaceRate_SpinBox_K2Node_ComponentBoundEvent_11_OnSpinBoxValueCommittedEvent__DelegateSignature(float InValue, ETextCommit CommitMethod);
	void BndEvt__WBP_MenuESC_Value_13_K2Node_ComponentBoundEvent_16_OnSpinBoxValueCommittedEvent__DelegateSignature(float InValue, ETextCommit CommitMethod);
	void BndEvt__WBP_MenuESC_Value_15_K2Node_ComponentBoundEvent_22_OnSpinBoxValueCommittedEvent__DelegateSignature(float InValue, ETextCommit CommitMethod);
	void BndEvt__WBP_MenuESC_Value_4_K2Node_ComponentBoundEvent_6_OnSpinBoxValueCommittedEvent__DelegateSignature(float InValue, ETextCommit CommitMethod);
	void BndEvt__WBP_MenuESC_Value_9_K2Node_ComponentBoundEvent_12_OnSpinBoxValueCommittedEvent__DelegateSignature(float InValue, ETextCommit CommitMethod);
	void BndEvt__WBP_MenuESC_WBP_PalInvisibleButton_CopyCode_K2Node_ComponentBoundEvent_25_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button);
	void BndEvt__WBP_MenuESC_WBP_PalInvisibleButton_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button);
	void ConfirmKill(bool Confirm);
	void ConfirmReturnTitle(bool Confirm);
	void CopyInviteCode();
	class UWidget* CustomNavi_ToInviteCode(EUINavigation Param_Navigation);
	class UWidget* CustomNavi_ToLeftMenuBottom(EUINavigation Param_Navigation);
	class UWidget* CustomNavi_ToLeftMenuTop(EUINavigation Param_Navigation);
	void ExecuteUbergraph_WBP_MenuESC(int32 EntryPoint);
	void InitOptionFieldBool(class UCheckBox* CheckBox, bool& CurrentValue);
	void InitOptionFieldFloat(const struct FPalOptionValueFloat& MinMaxValue, class USpinBox* SpinBox, double& CurrentValue);
	void InitOptionFieldInt(const struct FPalOptionValueInt& MinMaxValue, class USpinBox* SpinBox, int32& CurrentValue);
	void OnClickedButton(E_PalEscMenuType MenuType);
	void OnInitialized();
	void OnKillExecute();
	void OnReturn2Title();
	void ProcessSaveReturn();
	void SetInviteCodeText();
	void SetupWorldOptions();
	void ShowHideInviteCode();
	void UpdateRTT();

	class UWidget* BP_GetDesiredFocusTarget() const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_MenuESC_C">();
	}
	static class UWBP_MenuESC_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_MenuESC_C>();
	}
};
static_assert(alignof(UWBP_MenuESC_C) == 0x000008, "Wrong alignment on UWBP_MenuESC_C");
static_assert(sizeof(UWBP_MenuESC_C) == 0x000850, "Wrong size on UWBP_MenuESC_C");
static_assert(offsetof(UWBP_MenuESC_C, UberGraphFrame) == 0x000430, "Member 'UWBP_MenuESC_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_MenuESC_C, Anm_Clipboard_InToOut) == 0x000438, "Member 'UWBP_MenuESC_C::Anm_Clipboard_InToOut' has a wrong offset!");
static_assert(offsetof(UWBP_MenuESC_C, Anm_Copy_NormalToFocus) == 0x000440, "Member 'UWBP_MenuESC_C::Anm_Copy_NormalToFocus' has a wrong offset!");
static_assert(offsetof(UWBP_MenuESC_C, AimAssistKeyboard_CheckBox) == 0x000448, "Member 'UWBP_MenuESC_C::AimAssistKeyboard_CheckBox' has a wrong offset!");
static_assert(offsetof(UWBP_MenuESC_C, AimAssistPad_CheckBox) == 0x000450, "Member 'UWBP_MenuESC_C::AimAssistPad_CheckBox' has a wrong offset!");
static_assert(offsetof(UWBP_MenuESC_C, bActiveUNKO_CheckBox) == 0x000458, "Member 'UWBP_MenuESC_C::bActiveUNKO_CheckBox' has a wrong offset!");
static_assert(offsetof(UWBP_MenuESC_C, bEnableFriendlyFire_CheckBox) == 0x000460, "Member 'UWBP_MenuESC_C::bEnableFriendlyFire_CheckBox' has a wrong offset!");
static_assert(offsetof(UWBP_MenuESC_C, bEnableInvaderEnemy_CheckBox) == 0x000468, "Member 'UWBP_MenuESC_C::bEnableInvaderEnemy_CheckBox' has a wrong offset!");
static_assert(offsetof(UWBP_MenuESC_C, BP_PalRichTextBlock_MultiTips) == 0x000470, "Member 'UWBP_MenuESC_C::BP_PalRichTextBlock_MultiTips' has a wrong offset!");
static_assert(offsetof(UWBP_MenuESC_C, BPPalTextBlock_JitterNum) == 0x000478, "Member 'UWBP_MenuESC_C::BPPalTextBlock_JitterNum' has a wrong offset!");
static_assert(offsetof(UWBP_MenuESC_C, BPPalTextBlock_JoinNum) == 0x000480, "Member 'UWBP_MenuESC_C::BPPalTextBlock_JoinNum' has a wrong offset!");
static_assert(offsetof(UWBP_MenuESC_C, BPPalTextBlock_PacketlossNum) == 0x000488, "Member 'UWBP_MenuESC_C::BPPalTextBlock_PacketlossNum' has a wrong offset!");
static_assert(offsetof(UWBP_MenuESC_C, BPPalTextBlock_RTTNum) == 0x000490, "Member 'UWBP_MenuESC_C::BPPalTextBlock_RTTNum' has a wrong offset!");
static_assert(offsetof(UWBP_MenuESC_C, BPPalTextBlock_ServerFPSNum) == 0x000498, "Member 'UWBP_MenuESC_C::BPPalTextBlock_ServerFPSNum' has a wrong offset!");
static_assert(offsetof(UWBP_MenuESC_C, BPPalTextBlock_WorldExplain) == 0x0004A0, "Member 'UWBP_MenuESC_C::BPPalTextBlock_WorldExplain' has a wrong offset!");
static_assert(offsetof(UWBP_MenuESC_C, BPPalTextBlock_WorldName) == 0x0004A8, "Member 'UWBP_MenuESC_C::BPPalTextBlock_WorldName' has a wrong offset!");
static_assert(offsetof(UWBP_MenuESC_C, BuildObjectDamageRate_SpinBox) == 0x0004B0, "Member 'UWBP_MenuESC_C::BuildObjectDamageRate_SpinBox' has a wrong offset!");
static_assert(offsetof(UWBP_MenuESC_C, Canvas_Buttons) == 0x0004B8, "Member 'UWBP_MenuESC_C::Canvas_Buttons' has a wrong offset!");
static_assert(offsetof(UWBP_MenuESC_C, CanvasPanel_MultiTips) == 0x0004C0, "Member 'UWBP_MenuESC_C::CanvasPanel_MultiTips' has a wrong offset!");
static_assert(offsetof(UWBP_MenuESC_C, CollectionDropRate_SpinBox) == 0x0004C8, "Member 'UWBP_MenuESC_C::CollectionDropRate_SpinBox' has a wrong offset!");
static_assert(offsetof(UWBP_MenuESC_C, CollectionObjectHpRate_SpinBox) == 0x0004D0, "Member 'UWBP_MenuESC_C::CollectionObjectHpRate_SpinBox' has a wrong offset!");
static_assert(offsetof(UWBP_MenuESC_C, CollectionObjectRespawnSpeedRate) == 0x0004D8, "Member 'UWBP_MenuESC_C::CollectionObjectRespawnSpeedRate' has a wrong offset!");
static_assert(offsetof(UWBP_MenuESC_C, DayTimeSpeedRateValue_SpinBox) == 0x0004E0, "Member 'UWBP_MenuESC_C::DayTimeSpeedRateValue_SpinBox' has a wrong offset!");
static_assert(offsetof(UWBP_MenuESC_C, DeathPenalty_ComboBox) == 0x0004E8, "Member 'UWBP_MenuESC_C::DeathPenalty_ComboBox' has a wrong offset!");
static_assert(offsetof(UWBP_MenuESC_C, Difficulty_ComboBox) == 0x0004F0, "Member 'UWBP_MenuESC_C::Difficulty_ComboBox' has a wrong offset!");
static_assert(offsetof(UWBP_MenuESC_C, DropItemMaxNum_SpinBox) == 0x0004F8, "Member 'UWBP_MenuESC_C::DropItemMaxNum_SpinBox' has a wrong offset!");
static_assert(offsetof(UWBP_MenuESC_C, DropItemMaxNum_UNKO_SpinBox) == 0x000500, "Member 'UWBP_MenuESC_C::DropItemMaxNum_UNKO_SpinBox' has a wrong offset!");
static_assert(offsetof(UWBP_MenuESC_C, EnemyDropItemRate_SpinBox) == 0x000508, "Member 'UWBP_MenuESC_C::EnemyDropItemRate_SpinBox' has a wrong offset!");
static_assert(offsetof(UWBP_MenuESC_C, ExpRate_SpinBox) == 0x000510, "Member 'UWBP_MenuESC_C::ExpRate_SpinBox' has a wrong offset!");
static_assert(offsetof(UWBP_MenuESC_C, HorizontalBox_Jitter) == 0x000518, "Member 'UWBP_MenuESC_C::HorizontalBox_Jitter' has a wrong offset!");
static_assert(offsetof(UWBP_MenuESC_C, HorizontalBox_JoinNum) == 0x000520, "Member 'UWBP_MenuESC_C::HorizontalBox_JoinNum' has a wrong offset!");
static_assert(offsetof(UWBP_MenuESC_C, HorizontalBox_PacketLoss) == 0x000528, "Member 'UWBP_MenuESC_C::HorizontalBox_PacketLoss' has a wrong offset!");
static_assert(offsetof(UWBP_MenuESC_C, HorizontalBox_RTT) == 0x000530, "Member 'UWBP_MenuESC_C::HorizontalBox_RTT' has a wrong offset!");
static_assert(offsetof(UWBP_MenuESC_C, HorizontalBox_ServerFPS) == 0x000538, "Member 'UWBP_MenuESC_C::HorizontalBox_ServerFPS' has a wrong offset!");
static_assert(offsetof(UWBP_MenuESC_C, IconShowHide) == 0x000540, "Member 'UWBP_MenuESC_C::IconShowHide' has a wrong offset!");
static_assert(offsetof(UWBP_MenuESC_C, Image_115) == 0x000548, "Member 'UWBP_MenuESC_C::Image_115' has a wrong offset!");
static_assert(offsetof(UWBP_MenuESC_C, Image_CautionBase) == 0x000550, "Member 'UWBP_MenuESC_C::Image_CautionBase' has a wrong offset!");
static_assert(offsetof(UWBP_MenuESC_C, InviteCode_HorizontalBox) == 0x000558, "Member 'UWBP_MenuESC_C::InviteCode_HorizontalBox' has a wrong offset!");
static_assert(offsetof(UWBP_MenuESC_C, NightTimeSpeedRate_SpinBox) == 0x000560, "Member 'UWBP_MenuESC_C::NightTimeSpeedRate_SpinBox' has a wrong offset!");
static_assert(offsetof(UWBP_MenuESC_C, Overlay_WorldExplain) == 0x000568, "Member 'UWBP_MenuESC_C::Overlay_WorldExplain' has a wrong offset!");
static_assert(offsetof(UWBP_MenuESC_C, PalAutoHPRegeneRate_SpinBox) == 0x000570, "Member 'UWBP_MenuESC_C::PalAutoHPRegeneRate_SpinBox' has a wrong offset!");
static_assert(offsetof(UWBP_MenuESC_C, PalAutoHpRegeneRateInSleep_SpinBOx) == 0x000578, "Member 'UWBP_MenuESC_C::PalAutoHpRegeneRateInSleep_SpinBOx' has a wrong offset!");
static_assert(offsetof(UWBP_MenuESC_C, PalCaptureRateAdd_SpinBox) == 0x000580, "Member 'UWBP_MenuESC_C::PalCaptureRateAdd_SpinBox' has a wrong offset!");
static_assert(offsetof(UWBP_MenuESC_C, PalDamageRateAttack_SpinBox) == 0x000588, "Member 'UWBP_MenuESC_C::PalDamageRateAttack_SpinBox' has a wrong offset!");
static_assert(offsetof(UWBP_MenuESC_C, PalDamageRateDefense_SpinBox) == 0x000590, "Member 'UWBP_MenuESC_C::PalDamageRateDefense_SpinBox' has a wrong offset!");
static_assert(offsetof(UWBP_MenuESC_C, PalSpawnNumRate_SpinBox) == 0x000598, "Member 'UWBP_MenuESC_C::PalSpawnNumRate_SpinBox' has a wrong offset!");
static_assert(offsetof(UWBP_MenuESC_C, PalStaminaDecreaceRate) == 0x0005A0, "Member 'UWBP_MenuESC_C::PalStaminaDecreaceRate' has a wrong offset!");
static_assert(offsetof(UWBP_MenuESC_C, PalStomachDecreaceRate_SpinBox) == 0x0005A8, "Member 'UWBP_MenuESC_C::PalStomachDecreaceRate_SpinBox' has a wrong offset!");
static_assert(offsetof(UWBP_MenuESC_C, PlayerAutoHPRegeneRate_SpinBox) == 0x0005B0, "Member 'UWBP_MenuESC_C::PlayerAutoHPRegeneRate_SpinBox' has a wrong offset!");
static_assert(offsetof(UWBP_MenuESC_C, PlayerAutoHpRegeneRateInSleep_SpinBox) == 0x0005B8, "Member 'UWBP_MenuESC_C::PlayerAutoHpRegeneRateInSleep_SpinBox' has a wrong offset!");
static_assert(offsetof(UWBP_MenuESC_C, PlayerDamageRateAttack_SpinBox) == 0x0005C0, "Member 'UWBP_MenuESC_C::PlayerDamageRateAttack_SpinBox' has a wrong offset!");
static_assert(offsetof(UWBP_MenuESC_C, PlayerDamageRateDefense_SpinBox) == 0x0005C8, "Member 'UWBP_MenuESC_C::PlayerDamageRateDefense_SpinBox' has a wrong offset!");
static_assert(offsetof(UWBP_MenuESC_C, PlayerStaminaDecreaceRate) == 0x0005D0, "Member 'UWBP_MenuESC_C::PlayerStaminaDecreaceRate' has a wrong offset!");
static_assert(offsetof(UWBP_MenuESC_C, PlayerStomachDecreaceRate_SpinBox) == 0x0005D8, "Member 'UWBP_MenuESC_C::PlayerStomachDecreaceRate_SpinBox' has a wrong offset!");
static_assert(offsetof(UWBP_MenuESC_C, Text_InviteCode) == 0x0005E0, "Member 'UWBP_MenuESC_C::Text_InviteCode' has a wrong offset!");
static_assert(offsetof(UWBP_MenuESC_C, VerticalBox_ServerInfo) == 0x0005E8, "Member 'UWBP_MenuESC_C::VerticalBox_ServerInfo' has a wrong offset!");
static_assert(offsetof(UWBP_MenuESC_C, VerticalBoxWorld) == 0x0005F0, "Member 'UWBP_MenuESC_C::VerticalBoxWorld' has a wrong offset!");
static_assert(offsetof(UWBP_MenuESC_C, WBP_MenuESC_Button) == 0x0005F8, "Member 'UWBP_MenuESC_C::WBP_MenuESC_Button' has a wrong offset!");
static_assert(offsetof(UWBP_MenuESC_C, WBP_MenuESC_Button_1) == 0x000600, "Member 'UWBP_MenuESC_C::WBP_MenuESC_Button_1' has a wrong offset!");
static_assert(offsetof(UWBP_MenuESC_C, WBP_MenuESC_Button_2) == 0x000608, "Member 'UWBP_MenuESC_C::WBP_MenuESC_Button_2' has a wrong offset!");
static_assert(offsetof(UWBP_MenuESC_C, WBP_MenuESC_Button_3) == 0x000610, "Member 'UWBP_MenuESC_C::WBP_MenuESC_Button_3' has a wrong offset!");
static_assert(offsetof(UWBP_MenuESC_C, WBP_MenuESC_Button_4) == 0x000618, "Member 'UWBP_MenuESC_C::WBP_MenuESC_Button_4' has a wrong offset!");
static_assert(offsetof(UWBP_MenuESC_C, WBP_MenuESC_Button_5) == 0x000620, "Member 'UWBP_MenuESC_C::WBP_MenuESC_Button_5' has a wrong offset!");
static_assert(offsetof(UWBP_MenuESC_C, WBP_MenuESC_Button_6) == 0x000628, "Member 'UWBP_MenuESC_C::WBP_MenuESC_Button_6' has a wrong offset!");
static_assert(offsetof(UWBP_MenuESC_C, WBP_PalCommonScrollList_Members) == 0x000630, "Member 'UWBP_MenuESC_C::WBP_PalCommonScrollList_Members' has a wrong offset!");
static_assert(offsetof(UWBP_MenuESC_C, WBP_PalInvisibleButton_CopyCode) == 0x000638, "Member 'UWBP_MenuESC_C::WBP_PalInvisibleButton_CopyCode' has a wrong offset!");
static_assert(offsetof(UWBP_MenuESC_C, WBP_PalInvisibleButton_ShoiwHideInviteCode) == 0x000640, "Member 'UWBP_MenuESC_C::WBP_PalInvisibleButton_ShoiwHideInviteCode' has a wrong offset!");
static_assert(offsetof(UWBP_MenuESC_C, WorldOptionCanvas) == 0x000648, "Member 'UWBP_MenuESC_C::WorldOptionCanvas' has a wrong offset!");
static_assert(offsetof(UWBP_MenuESC_C, OptionWorldSettingsCache) == 0x000650, "Member 'UWBP_MenuESC_C::OptionWorldSettingsCache' has a wrong offset!");
static_assert(offsetof(UWBP_MenuESC_C, AudioSettingsCache) == 0x000788, "Member 'UWBP_MenuESC_C::AudioSettingsCache' has a wrong offset!");
static_assert(offsetof(UWBP_MenuESC_C, KeyboardSettingsCache) == 0x0007A4, "Member 'UWBP_MenuESC_C::KeyboardSettingsCache' has a wrong offset!");
static_assert(offsetof(UWBP_MenuESC_C, PadSettingsCache) == 0x0007B8, "Member 'UWBP_MenuESC_C::PadSettingsCache' has a wrong offset!");
static_assert(offsetof(UWBP_MenuESC_C, GraphicsSettingsCache) == 0x0007D4, "Member 'UWBP_MenuESC_C::GraphicsSettingsCache' has a wrong offset!");
static_assert(offsetof(UWBP_MenuESC_C, KillDialogMsgId) == 0x000828, "Member 'UWBP_MenuESC_C::KillDialogMsgId' has a wrong offset!");
static_assert(offsetof(UWBP_MenuESC_C, ToTitleDialogMsgId) == 0x000838, "Member 'UWBP_MenuESC_C::ToTitleDialogMsgId' has a wrong offset!");
static_assert(offsetof(UWBP_MenuESC_C, bShowInviteCode) == 0x000848, "Member 'UWBP_MenuESC_C::bShowInviteCode' has a wrong offset!");

}

