#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_PalCommonNewMark_0

#include "Basic.hpp"

#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_PalCommonNewMark_0.WBP_PalCommonNewMark_0_C
// 0x0008 (0x0280 - 0x0278)
class UWBP_PalCommonNewMark_0_C final : public UUserWidget
{
public:
	class UImage*                                 Image_118;                                         // 0x0278(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_PalCommonNewMark_0_C">();
	}
	static class UWBP_PalCommonNewMark_0_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_PalCommonNewMark_0_C>();
	}
};
static_assert(alignof(UWBP_PalCommonNewMark_0_C) == 0x000008, "Wrong alignment on UWBP_PalCommonNewMark_0_C");
static_assert(sizeof(UWBP_PalCommonNewMark_0_C) == 0x000280, "Wrong size on UWBP_PalCommonNewMark_0_C");
static_assert(offsetof(UWBP_PalCommonNewMark_0_C, Image_118) == 0x000278, "Member 'UWBP_PalCommonNewMark_0_C::Image_118' has a wrong offset!");

}

