#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MainMenu_Pal_00

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "E_PalUIStatusDIsplayParameter_structs.hpp"
#include "SlateCore_structs.hpp"
#include "Pal_structs.hpp"
#include "WBP_IndividualParameterBindWidget_classes.hpp"
#include "UMG_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_MainMenu_Pal_00.WBP_MainMenu_Pal_00_C
// 0x0540 (0x0AE0 - 0x05A0)
class UWBP_MainMenu_Pal_00_C final : public UWBP_IndividualParameterBindWidget_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_WBP_MainMenu_Pal_00_C;              // 0x05A0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       Anm_NoPal;                                         // 0x05A8(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Anm_Close_Status;                                  // 0x05B0(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Anm_Open_Status;                                   // 0x05B8(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Anm_Open_List;                                     // 0x05C0(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UBackgroundBlur*                        BackgroundBlur_Lock;                               // 0x05C8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBackgroundBlur*                        BackgroundBlur_Lock_1;                             // 0x05D0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBP_PalTextBlock_C*                     BP_PalTextBlock_C_2;                               // 0x05D8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBP_PalTextBlock_C*                     BP_PalTextBlock_LvText;                            // 0x05E0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBP_PalTextBlock_C*                     BP_PalTextBlock_NickName;                          // 0x05E8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBP_PalTextBlock_C*                     BP_PalTextBlock_SoulRank;                          // 0x05F0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCanvasPanel*                           Canvas_DropGuide;                                  // 0x05F8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCanvasPanel*                           Canvas_PalName;                                    // 0x0600(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCanvasPanel*                           Canvas_PalStatus;                                  // 0x0608(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCanvasPanel*                           Canvas_SkillInfo;                                  // 0x0610(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCanvasPanel*                           CanvasPanel_PartnerSkill;                          // 0x0618(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCanvasPanel*                           CanvasPanel_Potencial;                             // 0x0620(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCanvasPanel*                           CanvasPanelDebuff;                                 // 0x0628(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCanvasPanel*                           CanvasPanelLock_1;                                 // 0x0630(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCanvasPanel*                           CanvasPanelLockText;                               // 0x0638(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCanvasPanel*                           CanvasPanelLockText_1;                             // 0x0640(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UProgressBar*                           Gauge_Exp;                                         // 0x0648(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UProgressBar*                           Gauge_HP;                                          // 0x0650(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UProgressBar*                           Gauge_Hunger;                                      // 0x0658(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 IconRankArrow_Attack;                              // 0x0660(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 IconRankArrow_Defence;                             // 0x0668(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 IconRankArrow_Work;                                // 0x0670(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_PartnerSkill;                                // 0x0678(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_PartnerSkill_Sq;                             // 0x0680(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_PartnerSkillIcon;                            // 0x0688(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_PartnerSkillIcon_Sq;                         // 0x0690(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_Rare;                                        // 0x0698(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_Strong;                                      // 0x06A0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UOverlay*                               Overlay_Circle;                                    // 0x06A8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UOverlay*                               Overlay_Icon_Circle;                               // 0x06B0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UOverlay*                               Overlay_Icon_sq;                                   // 0x06B8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UOverlay*                               Overlay_sq;                                        // 0x06C0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBP_PalRichTextBlock_C*                 RichText_PartnerSkillDesc;                         // 0x06C8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBP_PalRichTextBlock_C*                 RichText_PartnerSkillDesc_1;                       // 0x06D0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBP_PalRichTextBlock_C*                 RichText_PartnerSkillName;                         // 0x06D8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBP_PalTextBlock_C*                     Text_DefenseValue;                                 // 0x06E0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBP_PalTextBlock_C*                     Text_LevelValue;                                   // 0x06E8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBP_PalTextBlock_C*                     Text_MaxHP;                                        // 0x06F0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBP_PalTextBlock_C*                     Text_MaxHunger;                                    // 0x06F8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBP_PalTextBlock_C*                     Text_NextExp;                                      // 0x0700(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBP_PalTextBlock_C*                     Text_NowHP;                                        // 0x0708(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBP_PalTextBlock_C*                     Text_NowHunger;                                    // 0x0710(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBP_PalTextBlock_C*                     Text_NowSanity;                                    // 0x0718(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBP_PalTextBlock_C*                     Text_PartnerSkillLevel_Value;                      // 0x0720(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBP_PalTextBlock_C*                     Text_PartnerSkillLevel_Value_1;                    // 0x0728(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBP_PalTextBlock_C*                     Text_PartnerSkillLockItem;                         // 0x0730(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBP_PalTextBlock_C*                     Text_PartnerSkillName_1;                           // 0x0738(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBP_PalTextBlock_C*                     Text_PunishedLevel_Af;                             // 0x0740(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBP_PalTextBlock_C*                     Text_PunishedLevel_Pre;                            // 0x0748(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBP_PalTextBlock_C*                     Text_RangeAttackValue;                             // 0x0750(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBP_PalTextBlock_C*                     Text_WorkSpeedValue;                               // 0x0758(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUniformGridPanel*                      UniformGrid_Suitability;                           // 0x0760(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVerticalBox*                           VerticalBox_Pal_List;                              // 0x0768(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVerticalBox*                           VerticalBox_Skill;                                 // 0x0770(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_CommonButton_C*                    WBP_CommonButton_NameEdit;                         // 0x0778(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_MainMenu_Pal_FoodAmount_C*         WBP_MainMenu_Pal_FoodAmount;                       // 0x0780(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_MainMenu_Pal_Skill_Active_C*       WBP_MainMenu_Pal_Skill_Active;                     // 0x0788(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_MainMenu_Pal_Skill_Active_C*       WBP_MainMenu_Pal_Skill_Active_1;                   // 0x0790(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_MainMenu_Pal_Skill_Active_C*       WBP_MainMenu_Pal_Skill_Active_2;                   // 0x0798(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_MainMenu_Pal_Skill_Passive_C*      WBP_MainMenu_Pal_Skill_Passive;                    // 0x07A0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_MainMenu_Pal_Skill_Passive_C*      WBP_MainMenu_Pal_Skill_Passive_1;                  // 0x07A8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_MainMenu_Pal_Skill_Passive_C*      WBP_MainMenu_Pal_Skill_Passive_2;                  // 0x07B0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_MainMenu_Pal_Skill_Passive_C*      WBP_MainMenu_Pal_Skill_Passive_3;                  // 0x07B8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_MainMenu_Pal_State_C*              WBP_MainMenu_Pal_State;                            // 0x07C0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_MainMenu_Pal_State_C*              WBP_MainMenu_Pal_State_0;                          // 0x07C8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_MainMenu_Pal_State_C*              WBP_MainMenu_Pal_State_1;                          // 0x07D0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_MainMenu_Pal_State_C*              WBP_MainMenu_Pal_State_2;                          // 0x07D8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_MainMenu_Pal_State_C*              WBP_MainMenu_Pal_State_3;                          // 0x07E0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_MainMenu_Pal_State_C*              WBP_MainMenu_Pal_State_4;                          // 0x07E8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_MainMenu_Pal_StatusElement_C*      WBP_MainMenu_Pal_StatusElement_000;                // 0x07F0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_MainMenu_Pal_StatusElement_C*      WBP_MainMenu_Pal_StatusElement_001;                // 0x07F8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_MainMenu_PalRarityStar_C*          WBP_MainMenu_PalRarityStar;                        // 0x0800(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_MainMenu_PalRarityStar_C*          WBP_MainMenu_PalRarityStar_1;                      // 0x0808(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_MainMenu_PalRarityStar_C*          WBP_MainMenu_PalRarityStar_2;                      // 0x0810(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_MainMenu_PalRarityStar_C*          WBP_MainMenu_PalRarityStar_3;                      // 0x0818(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_MainMenu_PalSkillInfo_C*           WBP_MainMenu_PalSkillInfo;                         // 0x0820(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Menu_Pal_Potencial_C*              WBP_Menu_Pal_Potencial;                            // 0x0828(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Menu_PalList_C*                    WBP_Menu_PalList;                                  // 0x0830(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Menu_PalList_C*                    WBP_Menu_PalList_1;                                // 0x0838(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Menu_PalList_C*                    WBP_Menu_PalList_2;                                // 0x0840(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Menu_PalList_C*                    WBP_Menu_PalList_3;                                // 0x0848(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Menu_PalList_C*                    WBP_Menu_PalList_4;                                // 0x0850(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Menu_PalList_C*                    WBP_Menu_PalList_5;                                // 0x0858(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_NoData_C*                          WBP_NoData;                                        // 0x0860(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_PalCommonButton_C*                 WBP_PalCommonButton_HP;                            // 0x0868(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_PalCommonButton_C*                 WBP_PalCommonButton_Hunger;                        // 0x0870(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_PalCommonButton_C*                 WBP_PalCommonButton_SAN;                           // 0x0878(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_PalGenderIcon_C*                   WBP_PalGenderIcon;                                 // 0x0880(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_PalInvisibleButton_C*              WBP_PalInvisibleButton_Atk;                        // 0x0888(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_PalInvisibleButton_C*              WBP_PalInvisibleButton_Def;                        // 0x0890(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_PalInvisibleButton_C*              WBP_PalInvisibleButton_LevelSync;                  // 0x0898(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_PalInvisibleButton_C*              WBP_PalInvisibleButton_Lock;                       // 0x08A0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_PalInvisibleButton_C*              WBP_PalInvisibleButton_Work;                       // 0x08A8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_PalKeyGuideIcon_C*                 WBP_PalKeyGuideIcon;                               // 0x08B0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_StatusBuffTimerContainer_C*        WBP_StatusBuffTimerContainer;                      // 0x08B8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	TArray<class UWBP_Menu_PalList_C*>            PalPanels;                                         // 0x08C0(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference)
	FMulticastInlineDelegateProperty_             OnClickedAnyPalPanel;                              // 0x08D0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	FMulticastInlineDelegateProperty_             OnHoveredAnyPalPanel;                              // 0x08E0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	bool                                          IsShowStatusWithList;                              // 0x08F0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_57F6[0x7];                                     // 0x08F1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UWBP_MainMenu_Pal_Skill_Active_C*> ActiveSkillPanelArray;                             // 0x08F8(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference)
	TArray<class UWBP_MainMenu_Pal_Skill_Passive_C*> PassiveSkillPanelArray;                            // 0x0908(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference)
	FMulticastInlineDelegateProperty_             OnUnhoveredAnyPalPanel;                            // 0x0918(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	FMulticastInlineDelegateProperty_             OnCommitedNickName;                                // 0x0928(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	FMulticastInlineDelegateProperty_             OnChangedNickname;                                 // 0x0938(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TArray<class UWBP_MainMenu_Pal_State_C*>      ConditionWidgetArray;                              // 0x0948(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference)
	struct FDataTableRowHandle                    HPParameterTitleMsgID;                             // 0x0958(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)
	struct FDataTableRowHandle                    HPParameterDescMsgID;                              // 0x0968(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)
	struct FDataTableRowHandle                    HungerParameterTitleMsgID;                         // 0x0978(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)
	struct FDataTableRowHandle                    HungerParameterDescMsgID;                          // 0x0988(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)
	struct FDataTableRowHandle                    SanityParameterTitleMsgID;                         // 0x0998(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)
	struct FDataTableRowHandle                    SanityParameterDescMsgID;                          // 0x09A8(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)
	struct FDataTableRowHandle                    GenusCategoryDescMsgID;                            // 0x09B8(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)
	TArray<class UWBP_MainMenu_Pal_State_C*>      SindeInfoConditionWidgetArray;                     // 0x09C8(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference)
	struct FDataTableRowHandle                    NoPalMsgID;                                        // 0x09D8(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)
	FMulticastInlineDelegateProperty_             OnSelectedChangeActiveSkill;                       // 0x09E8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	struct FDataTableRowHandle                    SkillUnlockMsgID;                                  // 0x09F8(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)
	class UPalIndividualCharacterHandle*          CachedIndividualHandle;                            // 0x0A08(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class UWBP_MainMenu_Pal_Skill_Active_C*       LastSelectedSkillPanel;                            // 0x0A10(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	TArray<class UWBP_MainMenu_PalRarityStar_C*>  RarityWidgetArray;                                 // 0x0A18(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference)
	struct FDataTableRowHandle                    PartnerSkillLockMsgID;                             // 0x0A28(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)
	struct FDataTableRowHandle                    DefTitleMsgID;                                     // 0x0A38(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)
	struct FDataTableRowHandle                    DefDescMsgID;                                      // 0x0A48(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)
	struct FDataTableRowHandle                    AtkTitleMsgID;                                     // 0x0A58(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)
	struct FDataTableRowHandle                    AtkDescMsgID;                                      // 0x0A68(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)
	struct FPalDataTableRowName_UIInputAction     RemoveWazaInputAction;                             // 0x0A78(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FPalUIActionBindData                   RemoveWazaActionHandle;                            // 0x0A80(0x0004)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)
	EPalWazaID                                    CachedSelectedWazaID;                              // 0x0A84(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_57F7[0x3];                                     // 0x0A85(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	FMulticastInlineDelegateProperty_             OnRequestedRemoveWaza;                             // 0x0A88(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	struct FDataTableRowHandle                    WorkTitleMsgID;                                    // 0x0A98(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)
	struct FDataTableRowHandle                    WorkDescMsgID;                                     // 0x0AA8(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)
	struct FDataTableRowHandle                    LevelSyncMsgID;                                    // 0x0AB8(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)
	struct FDataTableRowHandle                    LevelSyncDescMsgID;                                // 0x0AC8(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)
	bool                                          IsEditingNickName;                                 // 0x0AD8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void AnmEvent_HideSideInfo();
	void AnmEvent_NoPal();
	void AnmEvent_OpenList();
	void AnmEvent_ShowSideInfo();
	void AnmEvent_ToList();
	void AnmEvent_ToStatus();
	void AnmEvent_ToStatus_WithSetup(class UPalIndividualCharacterHandle* Handle);
	void Back_to_List();
	void BindFromHandle(class UPalIndividualCharacterHandle* TargetHandle);
	void BndEvt__WBP_MainMenu_Pal_00_WBP_CommonButton_NameEdit_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature();
	void BndEvt__WBP_MainMenu_Pal_00_WBP_MainMenu_Pal_Skill_Active_1_K2Node_ComponentBoundEvent_4_OnClicked__DelegateSignature(class UWBP_MainMenu_Pal_Skill_Active_C* SelfWidget);
	void BndEvt__WBP_MainMenu_Pal_00_WBP_MainMenu_Pal_Skill_Active_2_K2Node_ComponentBoundEvent_5_OnClicked__DelegateSignature(class UWBP_MainMenu_Pal_Skill_Active_C* SelfWidget);
	void BndEvt__WBP_MainMenu_Pal_00_WBP_MainMenu_Pal_Skill_Active_K2Node_ComponentBoundEvent_3_OnClicked__DelegateSignature(class UWBP_MainMenu_Pal_Skill_Active_C* SelfWidget);
	void BndEvt__WBP_MainMenu_Pal_00_WBP_PalCommonButton_HP_K2Node_ComponentBoundEvent_14_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button);
	void BndEvt__WBP_MainMenu_Pal_00_WBP_PalCommonButton_HP_K2Node_ComponentBoundEvent_15_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button);
	void BndEvt__WBP_MainMenu_Pal_00_WBP_PalCommonButton_Hunger_K2Node_ComponentBoundEvent_16_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button);
	void BndEvt__WBP_MainMenu_Pal_00_WBP_PalCommonButton_Hunger_K2Node_ComponentBoundEvent_17_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button);
	void BndEvt__WBP_MainMenu_Pal_00_WBP_PalCommonButton_SAN_K2Node_ComponentBoundEvent_18_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button);
	void BndEvt__WBP_MainMenu_Pal_00_WBP_PalCommonButton_SAN_K2Node_ComponentBoundEvent_19_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button);
	void BndEvt__WBP_MainMenu_Pal_00_WBP_PalInvisibleButton_Atk_K2Node_ComponentBoundEvent_8_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button);
	void BndEvt__WBP_MainMenu_Pal_00_WBP_PalInvisibleButton_Atk_K2Node_ComponentBoundEvent_9_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button);
	void BndEvt__WBP_MainMenu_Pal_00_WBP_PalInvisibleButton_Def_K2Node_ComponentBoundEvent_6_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button);
	void BndEvt__WBP_MainMenu_Pal_00_WBP_PalInvisibleButton_Def_K2Node_ComponentBoundEvent_7_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button);
	void BndEvt__WBP_MainMenu_Pal_00_WBP_PalInvisibleButton_K2Node_ComponentBoundEvent_12_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button);
	void BndEvt__WBP_MainMenu_Pal_00_WBP_PalInvisibleButton_K2Node_ComponentBoundEvent_13_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button);
	void BndEvt__WBP_MainMenu_Pal_00_WBP_PalInvisibleButton_LevelSync_K2Node_ComponentBoundEvent_22_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button);
	void BndEvt__WBP_MainMenu_Pal_00_WBP_PalInvisibleButton_LevelSync_K2Node_ComponentBoundEvent_23_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button);
	void BndEvt__WBP_MainMenu_Pal_00_WBP_PalInvisibleButton_Work_K2Node_ComponentBoundEvent_10_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button);
	void BndEvt__WBP_MainMenu_Pal_00_WBP_PalInvisibleButton_Work_K2Node_ComponentBoundEvent_11_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button);
	void Check_Valid_Work_Suitability(EPalWorkSuitability InWorkSuitability, bool* IsValid, EPalWorkSuitability* OutWorkSuitability, TArray<EPalMapObjectMaterialSubType>* MaterialSubTypes);
	void Close_Overlay_Info_Window();
	void CloseChangeActiveSkillList(class UPalHUDDispatchParameterBase* UPalHUDDispatchParam);
	void Construct();
	class UWidget* CustomNavi_ToActiveSkillTop(EUINavigation Param_Navigation);
	class UWidget* CustomNavi_ToFirstPassiveButton(EUINavigation Param_Navigation);
	class UWidget* CustomNavi_ToHPGuide(EUINavigation Param_Navigation);
	void ExecuteUbergraph_WBP_MainMenu_Pal_00(int32 EntryPoint);
	void Finished_3B3110DC440BFBD5CFED78B55117839E();
	void Finished_F11D370F4605F1875DFE3B9E5A74FBB3();
	void FocusToPalPanel(int32 Param_Index);
	void FocusToParameterPanel();
	void FocusToSkillPanel();
	void Get_Partner_Skill_Lock_Item_Name(class FName ItemId, class FText* ReturnText);
	void GetRestoreFocusSkillPanelTarget(class UWidget** TargetWidget);
	void IsShowingStatusWithList(bool* IsShowing);
	void ListToStatus(class UPalIndividualCharacterHandle* Handle);
	void OnChangedNickname__DelegateSignature(const class FText& EditingNickName);
	void OnClickedAnyPalPanel__DelegateSignature(class UPalIndividualCharacterHandle* Handle);
	void OnClickedPalButtonEvent(class UPalIndividualCharacterHandle* Handle);
	void OnCloseNameEditWindow(class UPalHUDDispatchParameterBase* Param_Param);
	void OnCommitedNickName__DelegateSignature(const class FText& NewNickName);
	void OnHoveredActiveSkillButtonEvent(class UWBP_MainMenu_Pal_Skill_Active_C* SelfWidget);
	void OnHoveredAnyPalPanel__DelegateSignature(class UPalIndividualCharacterHandle* Handle);
	void OnHoveredConditionButtonEvent(class UWBP_MainMenu_Pal_State_C* StateWidget);
	void OnHoveredPalButtonEvent(class UPalIndividualCharacterHandle* Handle);
	void OnHoveredPassiveSkillButtonEvent(class UWBP_MainMenu_Pal_Skill_Passive_C* SelfWidget);
	void OnInitialized();
	void OnRequestedRemoveWaza__DelegateSignature(EPalWazaID WazaID, class UPalIndividualCharacterHandle* TargetHandle);
	void OnSelectedChangeActiveSkill__DelegateSignature(class UPalIndividualCharacterHandle* TargetHandle, EPalWazaID ChangeWazaID, EPalWazaID NewWazaID);
	void OnSelectedSkill(EPalWazaID WazaID);
	void OnTriggeredRemoveWazaAction();
	void OnUnhoveredActiveSkillButtonEvent(class UWBP_MainMenu_Pal_Skill_Active_C* SelfWidget);
	void OnUnhoveredAnyPalPanel__DelegateSignature();
	void OnUnhoveredConditionButtonEvent(class UWBP_MainMenu_Pal_State_C* SelfWidget);
	void OnUnhoveredPalButtonEvent();
	void OnUnhoveredPassiveSkillButtonEvent(class UWBP_MainMenu_Pal_Skill_Passive_C* SelfWidget);
	void Open_Overlay_Info_Window(class UWidget* RelativeWidget, const struct FVector2D& AnchorPosition, const struct FVector2D& OverrideInfoWidgetAlignment, const class FText& Title, const class FText& Info, const class FText& SubInfo);
	void OpenChangeActiveSkillList(class UWBP_MainMenu_Pal_Skill_Active_C* SkillPanelWidget);
	void OpenNameEditWindow(const class FText& DefaultName);
	void OpenOverlaySkillInfoWindow(class UWBP_MainMenu_Pal_Skill_Active_C* RelativeWidget, const struct FVector2D& AnchorPosition, const struct FVector2D& OverrideInfoWidgetAlignment);
	void OpenOverlayStatusInfo(class UWidget* RelativeWidget, const struct FVector2D& AnchorPosition, const struct FVector2D& OverrideInfoWidgetAlignment, const class FText& Title, const class FText& Desc, E_PalUIStatusDIsplayParameter Status);
	void Set_Pal_Handles(TArray<class UPalIndividualCharacterHandle*>& Handles);
	void Set_Work_Suitability(const TMap<EPalWorkSuitability, int32>& WorkSuitabilities);
	void SetElementType(EPalElementType Type1, EPalElementType Type2);
	void SetFoodAmount(int32 FoodAmount);
	void SetGender(EPalGenderType GenderType);
	void SetPartnerSkillIcon(class FName CharacterID);
	void SetPartnerSkillLock(class FName CharacterID);
	void SetPassiveSkill(TArray<class FName>& PassiveSkills);
	void SetRank(int32 Rank);
	void SetRarity(bool IsBoss, bool IsRare);
	void SetSoulRank(int32 Rank);
	void Setup_Status(class UPalIndividualCharacterHandle* Handle);
	void SetupEvent();
	void Update_Buff_Binded();
	void Update_Buff_Status(class UPalIndividualCharacterParameter* Individual);
	void Update_Condition_Binded();
	void Update_Level_Binded(int32 NewLevel);
	void Update_Soul_Rank_Binded();
	void Update_Talent_Binded();
	void UpdateActiveSkill_Binded(TArray<EPalWazaID>& ActiveSkills);
	void UpdateExp_Binded(int32 AddExp, int32 OldExp, double NowExpRate);
	void UpdateHP_Binded(const struct FFixedPoint64& NowHP, const struct FFixedPoint64& NowMaxHP);
	void UpdateHunger_Binded(double NowHunger, double NowMaxHunger);
	void UpdateNickName_Binded(const class FString& NewNickName);
	void UpdateOverlaySkillInfoWindow();
	void UpdateSanity_Binded(double NowSanity, double NowMaxSanity);

	class UWidget* BP_GetDesiredFocusTarget() const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_MainMenu_Pal_00_C">();
	}
	static class UWBP_MainMenu_Pal_00_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_MainMenu_Pal_00_C>();
	}
};
static_assert(alignof(UWBP_MainMenu_Pal_00_C) == 0x000008, "Wrong alignment on UWBP_MainMenu_Pal_00_C");
static_assert(sizeof(UWBP_MainMenu_Pal_00_C) == 0x000AE0, "Wrong size on UWBP_MainMenu_Pal_00_C");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, UberGraphFrame_WBP_MainMenu_Pal_00_C) == 0x0005A0, "Member 'UWBP_MainMenu_Pal_00_C::UberGraphFrame_WBP_MainMenu_Pal_00_C' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, Anm_NoPal) == 0x0005A8, "Member 'UWBP_MainMenu_Pal_00_C::Anm_NoPal' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, Anm_Close_Status) == 0x0005B0, "Member 'UWBP_MainMenu_Pal_00_C::Anm_Close_Status' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, Anm_Open_Status) == 0x0005B8, "Member 'UWBP_MainMenu_Pal_00_C::Anm_Open_Status' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, Anm_Open_List) == 0x0005C0, "Member 'UWBP_MainMenu_Pal_00_C::Anm_Open_List' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, BackgroundBlur_Lock) == 0x0005C8, "Member 'UWBP_MainMenu_Pal_00_C::BackgroundBlur_Lock' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, BackgroundBlur_Lock_1) == 0x0005D0, "Member 'UWBP_MainMenu_Pal_00_C::BackgroundBlur_Lock_1' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, BP_PalTextBlock_C_2) == 0x0005D8, "Member 'UWBP_MainMenu_Pal_00_C::BP_PalTextBlock_C_2' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, BP_PalTextBlock_LvText) == 0x0005E0, "Member 'UWBP_MainMenu_Pal_00_C::BP_PalTextBlock_LvText' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, BP_PalTextBlock_NickName) == 0x0005E8, "Member 'UWBP_MainMenu_Pal_00_C::BP_PalTextBlock_NickName' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, BP_PalTextBlock_SoulRank) == 0x0005F0, "Member 'UWBP_MainMenu_Pal_00_C::BP_PalTextBlock_SoulRank' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, Canvas_DropGuide) == 0x0005F8, "Member 'UWBP_MainMenu_Pal_00_C::Canvas_DropGuide' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, Canvas_PalName) == 0x000600, "Member 'UWBP_MainMenu_Pal_00_C::Canvas_PalName' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, Canvas_PalStatus) == 0x000608, "Member 'UWBP_MainMenu_Pal_00_C::Canvas_PalStatus' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, Canvas_SkillInfo) == 0x000610, "Member 'UWBP_MainMenu_Pal_00_C::Canvas_SkillInfo' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, CanvasPanel_PartnerSkill) == 0x000618, "Member 'UWBP_MainMenu_Pal_00_C::CanvasPanel_PartnerSkill' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, CanvasPanel_Potencial) == 0x000620, "Member 'UWBP_MainMenu_Pal_00_C::CanvasPanel_Potencial' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, CanvasPanelDebuff) == 0x000628, "Member 'UWBP_MainMenu_Pal_00_C::CanvasPanelDebuff' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, CanvasPanelLock_1) == 0x000630, "Member 'UWBP_MainMenu_Pal_00_C::CanvasPanelLock_1' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, CanvasPanelLockText) == 0x000638, "Member 'UWBP_MainMenu_Pal_00_C::CanvasPanelLockText' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, CanvasPanelLockText_1) == 0x000640, "Member 'UWBP_MainMenu_Pal_00_C::CanvasPanelLockText_1' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, Gauge_Exp) == 0x000648, "Member 'UWBP_MainMenu_Pal_00_C::Gauge_Exp' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, Gauge_HP) == 0x000650, "Member 'UWBP_MainMenu_Pal_00_C::Gauge_HP' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, Gauge_Hunger) == 0x000658, "Member 'UWBP_MainMenu_Pal_00_C::Gauge_Hunger' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, IconRankArrow_Attack) == 0x000660, "Member 'UWBP_MainMenu_Pal_00_C::IconRankArrow_Attack' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, IconRankArrow_Defence) == 0x000668, "Member 'UWBP_MainMenu_Pal_00_C::IconRankArrow_Defence' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, IconRankArrow_Work) == 0x000670, "Member 'UWBP_MainMenu_Pal_00_C::IconRankArrow_Work' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, Image_PartnerSkill) == 0x000678, "Member 'UWBP_MainMenu_Pal_00_C::Image_PartnerSkill' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, Image_PartnerSkill_Sq) == 0x000680, "Member 'UWBP_MainMenu_Pal_00_C::Image_PartnerSkill_Sq' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, Image_PartnerSkillIcon) == 0x000688, "Member 'UWBP_MainMenu_Pal_00_C::Image_PartnerSkillIcon' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, Image_PartnerSkillIcon_Sq) == 0x000690, "Member 'UWBP_MainMenu_Pal_00_C::Image_PartnerSkillIcon_Sq' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, Image_Rare) == 0x000698, "Member 'UWBP_MainMenu_Pal_00_C::Image_Rare' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, Image_Strong) == 0x0006A0, "Member 'UWBP_MainMenu_Pal_00_C::Image_Strong' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, Overlay_Circle) == 0x0006A8, "Member 'UWBP_MainMenu_Pal_00_C::Overlay_Circle' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, Overlay_Icon_Circle) == 0x0006B0, "Member 'UWBP_MainMenu_Pal_00_C::Overlay_Icon_Circle' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, Overlay_Icon_sq) == 0x0006B8, "Member 'UWBP_MainMenu_Pal_00_C::Overlay_Icon_sq' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, Overlay_sq) == 0x0006C0, "Member 'UWBP_MainMenu_Pal_00_C::Overlay_sq' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, RichText_PartnerSkillDesc) == 0x0006C8, "Member 'UWBP_MainMenu_Pal_00_C::RichText_PartnerSkillDesc' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, RichText_PartnerSkillDesc_1) == 0x0006D0, "Member 'UWBP_MainMenu_Pal_00_C::RichText_PartnerSkillDesc_1' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, RichText_PartnerSkillName) == 0x0006D8, "Member 'UWBP_MainMenu_Pal_00_C::RichText_PartnerSkillName' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, Text_DefenseValue) == 0x0006E0, "Member 'UWBP_MainMenu_Pal_00_C::Text_DefenseValue' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, Text_LevelValue) == 0x0006E8, "Member 'UWBP_MainMenu_Pal_00_C::Text_LevelValue' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, Text_MaxHP) == 0x0006F0, "Member 'UWBP_MainMenu_Pal_00_C::Text_MaxHP' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, Text_MaxHunger) == 0x0006F8, "Member 'UWBP_MainMenu_Pal_00_C::Text_MaxHunger' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, Text_NextExp) == 0x000700, "Member 'UWBP_MainMenu_Pal_00_C::Text_NextExp' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, Text_NowHP) == 0x000708, "Member 'UWBP_MainMenu_Pal_00_C::Text_NowHP' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, Text_NowHunger) == 0x000710, "Member 'UWBP_MainMenu_Pal_00_C::Text_NowHunger' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, Text_NowSanity) == 0x000718, "Member 'UWBP_MainMenu_Pal_00_C::Text_NowSanity' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, Text_PartnerSkillLevel_Value) == 0x000720, "Member 'UWBP_MainMenu_Pal_00_C::Text_PartnerSkillLevel_Value' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, Text_PartnerSkillLevel_Value_1) == 0x000728, "Member 'UWBP_MainMenu_Pal_00_C::Text_PartnerSkillLevel_Value_1' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, Text_PartnerSkillLockItem) == 0x000730, "Member 'UWBP_MainMenu_Pal_00_C::Text_PartnerSkillLockItem' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, Text_PartnerSkillName_1) == 0x000738, "Member 'UWBP_MainMenu_Pal_00_C::Text_PartnerSkillName_1' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, Text_PunishedLevel_Af) == 0x000740, "Member 'UWBP_MainMenu_Pal_00_C::Text_PunishedLevel_Af' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, Text_PunishedLevel_Pre) == 0x000748, "Member 'UWBP_MainMenu_Pal_00_C::Text_PunishedLevel_Pre' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, Text_RangeAttackValue) == 0x000750, "Member 'UWBP_MainMenu_Pal_00_C::Text_RangeAttackValue' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, Text_WorkSpeedValue) == 0x000758, "Member 'UWBP_MainMenu_Pal_00_C::Text_WorkSpeedValue' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, UniformGrid_Suitability) == 0x000760, "Member 'UWBP_MainMenu_Pal_00_C::UniformGrid_Suitability' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, VerticalBox_Pal_List) == 0x000768, "Member 'UWBP_MainMenu_Pal_00_C::VerticalBox_Pal_List' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, VerticalBox_Skill) == 0x000770, "Member 'UWBP_MainMenu_Pal_00_C::VerticalBox_Skill' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, WBP_CommonButton_NameEdit) == 0x000778, "Member 'UWBP_MainMenu_Pal_00_C::WBP_CommonButton_NameEdit' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, WBP_MainMenu_Pal_FoodAmount) == 0x000780, "Member 'UWBP_MainMenu_Pal_00_C::WBP_MainMenu_Pal_FoodAmount' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, WBP_MainMenu_Pal_Skill_Active) == 0x000788, "Member 'UWBP_MainMenu_Pal_00_C::WBP_MainMenu_Pal_Skill_Active' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, WBP_MainMenu_Pal_Skill_Active_1) == 0x000790, "Member 'UWBP_MainMenu_Pal_00_C::WBP_MainMenu_Pal_Skill_Active_1' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, WBP_MainMenu_Pal_Skill_Active_2) == 0x000798, "Member 'UWBP_MainMenu_Pal_00_C::WBP_MainMenu_Pal_Skill_Active_2' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, WBP_MainMenu_Pal_Skill_Passive) == 0x0007A0, "Member 'UWBP_MainMenu_Pal_00_C::WBP_MainMenu_Pal_Skill_Passive' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, WBP_MainMenu_Pal_Skill_Passive_1) == 0x0007A8, "Member 'UWBP_MainMenu_Pal_00_C::WBP_MainMenu_Pal_Skill_Passive_1' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, WBP_MainMenu_Pal_Skill_Passive_2) == 0x0007B0, "Member 'UWBP_MainMenu_Pal_00_C::WBP_MainMenu_Pal_Skill_Passive_2' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, WBP_MainMenu_Pal_Skill_Passive_3) == 0x0007B8, "Member 'UWBP_MainMenu_Pal_00_C::WBP_MainMenu_Pal_Skill_Passive_3' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, WBP_MainMenu_Pal_State) == 0x0007C0, "Member 'UWBP_MainMenu_Pal_00_C::WBP_MainMenu_Pal_State' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, WBP_MainMenu_Pal_State_0) == 0x0007C8, "Member 'UWBP_MainMenu_Pal_00_C::WBP_MainMenu_Pal_State_0' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, WBP_MainMenu_Pal_State_1) == 0x0007D0, "Member 'UWBP_MainMenu_Pal_00_C::WBP_MainMenu_Pal_State_1' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, WBP_MainMenu_Pal_State_2) == 0x0007D8, "Member 'UWBP_MainMenu_Pal_00_C::WBP_MainMenu_Pal_State_2' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, WBP_MainMenu_Pal_State_3) == 0x0007E0, "Member 'UWBP_MainMenu_Pal_00_C::WBP_MainMenu_Pal_State_3' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, WBP_MainMenu_Pal_State_4) == 0x0007E8, "Member 'UWBP_MainMenu_Pal_00_C::WBP_MainMenu_Pal_State_4' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, WBP_MainMenu_Pal_StatusElement_000) == 0x0007F0, "Member 'UWBP_MainMenu_Pal_00_C::WBP_MainMenu_Pal_StatusElement_000' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, WBP_MainMenu_Pal_StatusElement_001) == 0x0007F8, "Member 'UWBP_MainMenu_Pal_00_C::WBP_MainMenu_Pal_StatusElement_001' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, WBP_MainMenu_PalRarityStar) == 0x000800, "Member 'UWBP_MainMenu_Pal_00_C::WBP_MainMenu_PalRarityStar' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, WBP_MainMenu_PalRarityStar_1) == 0x000808, "Member 'UWBP_MainMenu_Pal_00_C::WBP_MainMenu_PalRarityStar_1' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, WBP_MainMenu_PalRarityStar_2) == 0x000810, "Member 'UWBP_MainMenu_Pal_00_C::WBP_MainMenu_PalRarityStar_2' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, WBP_MainMenu_PalRarityStar_3) == 0x000818, "Member 'UWBP_MainMenu_Pal_00_C::WBP_MainMenu_PalRarityStar_3' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, WBP_MainMenu_PalSkillInfo) == 0x000820, "Member 'UWBP_MainMenu_Pal_00_C::WBP_MainMenu_PalSkillInfo' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, WBP_Menu_Pal_Potencial) == 0x000828, "Member 'UWBP_MainMenu_Pal_00_C::WBP_Menu_Pal_Potencial' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, WBP_Menu_PalList) == 0x000830, "Member 'UWBP_MainMenu_Pal_00_C::WBP_Menu_PalList' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, WBP_Menu_PalList_1) == 0x000838, "Member 'UWBP_MainMenu_Pal_00_C::WBP_Menu_PalList_1' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, WBP_Menu_PalList_2) == 0x000840, "Member 'UWBP_MainMenu_Pal_00_C::WBP_Menu_PalList_2' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, WBP_Menu_PalList_3) == 0x000848, "Member 'UWBP_MainMenu_Pal_00_C::WBP_Menu_PalList_3' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, WBP_Menu_PalList_4) == 0x000850, "Member 'UWBP_MainMenu_Pal_00_C::WBP_Menu_PalList_4' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, WBP_Menu_PalList_5) == 0x000858, "Member 'UWBP_MainMenu_Pal_00_C::WBP_Menu_PalList_5' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, WBP_NoData) == 0x000860, "Member 'UWBP_MainMenu_Pal_00_C::WBP_NoData' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, WBP_PalCommonButton_HP) == 0x000868, "Member 'UWBP_MainMenu_Pal_00_C::WBP_PalCommonButton_HP' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, WBP_PalCommonButton_Hunger) == 0x000870, "Member 'UWBP_MainMenu_Pal_00_C::WBP_PalCommonButton_Hunger' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, WBP_PalCommonButton_SAN) == 0x000878, "Member 'UWBP_MainMenu_Pal_00_C::WBP_PalCommonButton_SAN' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, WBP_PalGenderIcon) == 0x000880, "Member 'UWBP_MainMenu_Pal_00_C::WBP_PalGenderIcon' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, WBP_PalInvisibleButton_Atk) == 0x000888, "Member 'UWBP_MainMenu_Pal_00_C::WBP_PalInvisibleButton_Atk' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, WBP_PalInvisibleButton_Def) == 0x000890, "Member 'UWBP_MainMenu_Pal_00_C::WBP_PalInvisibleButton_Def' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, WBP_PalInvisibleButton_LevelSync) == 0x000898, "Member 'UWBP_MainMenu_Pal_00_C::WBP_PalInvisibleButton_LevelSync' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, WBP_PalInvisibleButton_Lock) == 0x0008A0, "Member 'UWBP_MainMenu_Pal_00_C::WBP_PalInvisibleButton_Lock' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, WBP_PalInvisibleButton_Work) == 0x0008A8, "Member 'UWBP_MainMenu_Pal_00_C::WBP_PalInvisibleButton_Work' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, WBP_PalKeyGuideIcon) == 0x0008B0, "Member 'UWBP_MainMenu_Pal_00_C::WBP_PalKeyGuideIcon' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, WBP_StatusBuffTimerContainer) == 0x0008B8, "Member 'UWBP_MainMenu_Pal_00_C::WBP_StatusBuffTimerContainer' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, PalPanels) == 0x0008C0, "Member 'UWBP_MainMenu_Pal_00_C::PalPanels' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, OnClickedAnyPalPanel) == 0x0008D0, "Member 'UWBP_MainMenu_Pal_00_C::OnClickedAnyPalPanel' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, OnHoveredAnyPalPanel) == 0x0008E0, "Member 'UWBP_MainMenu_Pal_00_C::OnHoveredAnyPalPanel' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, IsShowStatusWithList) == 0x0008F0, "Member 'UWBP_MainMenu_Pal_00_C::IsShowStatusWithList' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, ActiveSkillPanelArray) == 0x0008F8, "Member 'UWBP_MainMenu_Pal_00_C::ActiveSkillPanelArray' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, PassiveSkillPanelArray) == 0x000908, "Member 'UWBP_MainMenu_Pal_00_C::PassiveSkillPanelArray' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, OnUnhoveredAnyPalPanel) == 0x000918, "Member 'UWBP_MainMenu_Pal_00_C::OnUnhoveredAnyPalPanel' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, OnCommitedNickName) == 0x000928, "Member 'UWBP_MainMenu_Pal_00_C::OnCommitedNickName' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, OnChangedNickname) == 0x000938, "Member 'UWBP_MainMenu_Pal_00_C::OnChangedNickname' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, ConditionWidgetArray) == 0x000948, "Member 'UWBP_MainMenu_Pal_00_C::ConditionWidgetArray' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, HPParameterTitleMsgID) == 0x000958, "Member 'UWBP_MainMenu_Pal_00_C::HPParameterTitleMsgID' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, HPParameterDescMsgID) == 0x000968, "Member 'UWBP_MainMenu_Pal_00_C::HPParameterDescMsgID' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, HungerParameterTitleMsgID) == 0x000978, "Member 'UWBP_MainMenu_Pal_00_C::HungerParameterTitleMsgID' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, HungerParameterDescMsgID) == 0x000988, "Member 'UWBP_MainMenu_Pal_00_C::HungerParameterDescMsgID' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, SanityParameterTitleMsgID) == 0x000998, "Member 'UWBP_MainMenu_Pal_00_C::SanityParameterTitleMsgID' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, SanityParameterDescMsgID) == 0x0009A8, "Member 'UWBP_MainMenu_Pal_00_C::SanityParameterDescMsgID' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, GenusCategoryDescMsgID) == 0x0009B8, "Member 'UWBP_MainMenu_Pal_00_C::GenusCategoryDescMsgID' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, SindeInfoConditionWidgetArray) == 0x0009C8, "Member 'UWBP_MainMenu_Pal_00_C::SindeInfoConditionWidgetArray' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, NoPalMsgID) == 0x0009D8, "Member 'UWBP_MainMenu_Pal_00_C::NoPalMsgID' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, OnSelectedChangeActiveSkill) == 0x0009E8, "Member 'UWBP_MainMenu_Pal_00_C::OnSelectedChangeActiveSkill' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, SkillUnlockMsgID) == 0x0009F8, "Member 'UWBP_MainMenu_Pal_00_C::SkillUnlockMsgID' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, CachedIndividualHandle) == 0x000A08, "Member 'UWBP_MainMenu_Pal_00_C::CachedIndividualHandle' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, LastSelectedSkillPanel) == 0x000A10, "Member 'UWBP_MainMenu_Pal_00_C::LastSelectedSkillPanel' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, RarityWidgetArray) == 0x000A18, "Member 'UWBP_MainMenu_Pal_00_C::RarityWidgetArray' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, PartnerSkillLockMsgID) == 0x000A28, "Member 'UWBP_MainMenu_Pal_00_C::PartnerSkillLockMsgID' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, DefTitleMsgID) == 0x000A38, "Member 'UWBP_MainMenu_Pal_00_C::DefTitleMsgID' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, DefDescMsgID) == 0x000A48, "Member 'UWBP_MainMenu_Pal_00_C::DefDescMsgID' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, AtkTitleMsgID) == 0x000A58, "Member 'UWBP_MainMenu_Pal_00_C::AtkTitleMsgID' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, AtkDescMsgID) == 0x000A68, "Member 'UWBP_MainMenu_Pal_00_C::AtkDescMsgID' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, RemoveWazaInputAction) == 0x000A78, "Member 'UWBP_MainMenu_Pal_00_C::RemoveWazaInputAction' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, RemoveWazaActionHandle) == 0x000A80, "Member 'UWBP_MainMenu_Pal_00_C::RemoveWazaActionHandle' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, CachedSelectedWazaID) == 0x000A84, "Member 'UWBP_MainMenu_Pal_00_C::CachedSelectedWazaID' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, OnRequestedRemoveWaza) == 0x000A88, "Member 'UWBP_MainMenu_Pal_00_C::OnRequestedRemoveWaza' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, WorkTitleMsgID) == 0x000A98, "Member 'UWBP_MainMenu_Pal_00_C::WorkTitleMsgID' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, WorkDescMsgID) == 0x000AA8, "Member 'UWBP_MainMenu_Pal_00_C::WorkDescMsgID' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, LevelSyncMsgID) == 0x000AB8, "Member 'UWBP_MainMenu_Pal_00_C::LevelSyncMsgID' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, LevelSyncDescMsgID) == 0x000AC8, "Member 'UWBP_MainMenu_Pal_00_C::LevelSyncDescMsgID' has a wrong offset!");
static_assert(offsetof(UWBP_MainMenu_Pal_00_C, IsEditingNickName) == 0x000AD8, "Member 'UWBP_MainMenu_Pal_00_C::IsEditingNickName' has a wrong offset!");

}

