#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_IngameMenuConstruction_TabSub

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function WBP_IngameMenuConstruction_TabSub.WBP_IngameMenuConstruction_TabSub_C.SetActive
// 0x0014 (0x0014 - 0x0000)
struct WBP_IngameMenuConstruction_TabSub_C_SetActive final
{
public:
	bool                                          IsActive;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4F4F[0x3];                                     // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLinearColor                           CallFunc_SelectColor_ReturnValue;                  // 0x0004(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_IngameMenuConstruction_TabSub_C_SetActive) == 0x000004, "Wrong alignment on WBP_IngameMenuConstruction_TabSub_C_SetActive");
static_assert(sizeof(WBP_IngameMenuConstruction_TabSub_C_SetActive) == 0x000014, "Wrong size on WBP_IngameMenuConstruction_TabSub_C_SetActive");
static_assert(offsetof(WBP_IngameMenuConstruction_TabSub_C_SetActive, IsActive) == 0x000000, "Member 'WBP_IngameMenuConstruction_TabSub_C_SetActive::IsActive' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenuConstruction_TabSub_C_SetActive, CallFunc_SelectColor_ReturnValue) == 0x000004, "Member 'WBP_IngameMenuConstruction_TabSub_C_SetActive::CallFunc_SelectColor_ReturnValue' has a wrong offset!");

}

