#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_IngameMenu_Monitoring

#include "Basic.hpp"

#include "WBP_IngameMenu_Monitoring_classes.hpp"
#include "WBP_IngameMenu_Monitoring_parameters.hpp"


namespace SDK
{

// Function WBP_IngameMenu_Monitoring.WBP_IngameMenu_Monitoring_C.BndEvt__WBP_IngameMenu_Monitoring_WBP_Menu_btn_K2Node_ComponentBoundEvent_0_OnButtonClicked__DelegateSignature
// (BlueprintEvent)

void UWBP_IngameMenu_Monitoring_C::BndEvt__WBP_IngameMenu_Monitoring_WBP_Menu_btn_K2Node_ComponentBoundEvent_0_OnButtonClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_IngameMenu_Monitoring_C", "BndEvt__WBP_IngameMenu_Monitoring_WBP_Menu_btn_K2Node_ComponentBoundEvent_0_OnButtonClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_IngameMenu_Monitoring.WBP_IngameMenu_Monitoring_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_IngameMenu_Monitoring_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_IngameMenu_Monitoring_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_IngameMenu_Monitoring.WBP_IngameMenu_Monitoring_C.DisplayCurrentWorkHardInfo
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWBP_IngameMenu_Monitoring_C::DisplayCurrentWorkHardInfo()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_IngameMenu_Monitoring_C", "DisplayCurrentWorkHardInfo");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_IngameMenu_Monitoring.WBP_IngameMenu_Monitoring_C.DisplayHoverWorkHardInfo
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Param_WorkHardLevel                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_IngameMenu_Monitoring_C::DisplayHoverWorkHardInfo(int32 Param_WorkHardLevel)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_IngameMenu_Monitoring_C", "DisplayHoverWorkHardInfo");

	Params::WBP_IngameMenu_Monitoring_C_DisplayHoverWorkHardInfo Parms{};

	Parms.Param_WorkHardLevel = Param_WorkHardLevel;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_IngameMenu_Monitoring.WBP_IngameMenu_Monitoring_C.ExecuteUbergraph_WBP_IngameMenu_Monitoring
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_IngameMenu_Monitoring_C::ExecuteUbergraph_WBP_IngameMenu_Monitoring(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_IngameMenu_Monitoring_C", "ExecuteUbergraph_WBP_IngameMenu_Monitoring");

	Params::WBP_IngameMenu_Monitoring_C_ExecuteUbergraph_WBP_IngameMenu_Monitoring Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_IngameMenu_Monitoring.WBP_IngameMenu_Monitoring_C.OnSetup
// (Event, Protected, BlueprintCallable, BlueprintEvent)

void UWBP_IngameMenu_Monitoring_C::OnSetup()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_IngameMenu_Monitoring_C", "OnSetup");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_IngameMenu_Monitoring.WBP_IngameMenu_Monitoring_C.OnUpdateWorkHardType
// (Private, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UPalBaseCampPassiveEffect_WorkHard*EffectWorkHard                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_IngameMenu_Monitoring_C::OnUpdateWorkHardType(class UPalBaseCampPassiveEffect_WorkHard* EffectWorkHard)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_IngameMenu_Monitoring_C", "OnUpdateWorkHardType");

	Params::WBP_IngameMenu_Monitoring_C_OnUpdateWorkHardType Parms{};

	Parms.EffectWorkHard = EffectWorkHard;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_IngameMenu_Monitoring.WBP_IngameMenu_Monitoring_C.RequestChangeHardWorkLevel
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Level                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_IngameMenu_Monitoring_C::RequestChangeHardWorkLevel(int32 Level)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_IngameMenu_Monitoring_C", "RequestChangeHardWorkLevel");

	Params::WBP_IngameMenu_Monitoring_C_RequestChangeHardWorkLevel Parms{};

	Parms.Level = Level;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_IngameMenu_Monitoring.WBP_IngameMenu_Monitoring_C.UpdateWorkHardInfo
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Param_WorkHardLevel                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_IngameMenu_Monitoring_C::UpdateWorkHardInfo(int32 Param_WorkHardLevel)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_IngameMenu_Monitoring_C", "UpdateWorkHardInfo");

	Params::WBP_IngameMenu_Monitoring_C_UpdateWorkHardInfo Parms{};

	Parms.Param_WorkHardLevel = Param_WorkHardLevel;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_IngameMenu_Monitoring.WBP_IngameMenu_Monitoring_C.BP_GetDesiredFocusTarget
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)

class UWidget* UWBP_IngameMenu_Monitoring_C::BP_GetDesiredFocusTarget() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_IngameMenu_Monitoring_C", "BP_GetDesiredFocusTarget");

	Params::WBP_IngameMenu_Monitoring_C_BP_GetDesiredFocusTarget Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

