#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_WorkerRadialMenuContent

#include "Basic.hpp"

#include "WBP_WorkerRadialMenuContent_classes.hpp"
#include "WBP_WorkerRadialMenuContent_parameters.hpp"


namespace SDK
{

// Function WBP_WorkerRadialMenuContent.WBP_WorkerRadialMenuContent_C.SetText
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FText                             Text                                                   (BlueprintVisible, BlueprintReadOnly, Parm)

void UWBP_WorkerRadialMenuContent_C::SetText(const class FText& Text)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_WorkerRadialMenuContent_C", "SetText");

	Params::WBP_WorkerRadialMenuContent_C_SetText Parms{};

	Parms.Text = std::move(Text);

	UObject::ProcessEvent(Func, &Parms);
}

}

