#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_TechnologyUI

#include "Basic.hpp"

#include "Pal_structs.hpp"
#include "SlateCore_structs.hpp"
#include "EPalUIInGameMainMenuTabType_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "UMG_structs.hpp"
#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function WBP_TechnologyUI.WBP_TechnologyUI_C.BndEvt__WBP_TechnologyUI_WBP_MainMenu_Technology_00_K2Node_ComponentBoundEvent_3_OnClickedTchnology__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct WBP_TechnologyUI_C_BndEvt__WBP_TechnologyUI_WBP_MainMenu_Technology_00_K2Node_ComponentBoundEvent_3_OnClickedTchnology__DelegateSignature final
{
public:
	class UWBP_MainMenu_Technology_Content_C*     Widget;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_TechnologyUI_C_BndEvt__WBP_TechnologyUI_WBP_MainMenu_Technology_00_K2Node_ComponentBoundEvent_3_OnClickedTchnology__DelegateSignature) == 0x000008, "Wrong alignment on WBP_TechnologyUI_C_BndEvt__WBP_TechnologyUI_WBP_MainMenu_Technology_00_K2Node_ComponentBoundEvent_3_OnClickedTchnology__DelegateSignature");
static_assert(sizeof(WBP_TechnologyUI_C_BndEvt__WBP_TechnologyUI_WBP_MainMenu_Technology_00_K2Node_ComponentBoundEvent_3_OnClickedTchnology__DelegateSignature) == 0x000008, "Wrong size on WBP_TechnologyUI_C_BndEvt__WBP_TechnologyUI_WBP_MainMenu_Technology_00_K2Node_ComponentBoundEvent_3_OnClickedTchnology__DelegateSignature");
static_assert(offsetof(WBP_TechnologyUI_C_BndEvt__WBP_TechnologyUI_WBP_MainMenu_Technology_00_K2Node_ComponentBoundEvent_3_OnClickedTchnology__DelegateSignature, Widget) == 0x000000, "Member 'WBP_TechnologyUI_C_BndEvt__WBP_TechnologyUI_WBP_MainMenu_Technology_00_K2Node_ComponentBoundEvent_3_OnClickedTchnology__DelegateSignature::Widget' has a wrong offset!");

// Function WBP_TechnologyUI.WBP_TechnologyUI_C.BndEvt__WBP_TechnologyUI_WBP_MainMenu_Technology_00_K2Node_ComponentBoundEvent_4_OnHoveredTechnology__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct WBP_TechnologyUI_C_BndEvt__WBP_TechnologyUI_WBP_MainMenu_Technology_00_K2Node_ComponentBoundEvent_4_OnHoveredTechnology__DelegateSignature final
{
public:
	class UWBP_MainMenu_Technology_Content_C*     Widget;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_TechnologyUI_C_BndEvt__WBP_TechnologyUI_WBP_MainMenu_Technology_00_K2Node_ComponentBoundEvent_4_OnHoveredTechnology__DelegateSignature) == 0x000008, "Wrong alignment on WBP_TechnologyUI_C_BndEvt__WBP_TechnologyUI_WBP_MainMenu_Technology_00_K2Node_ComponentBoundEvent_4_OnHoveredTechnology__DelegateSignature");
static_assert(sizeof(WBP_TechnologyUI_C_BndEvt__WBP_TechnologyUI_WBP_MainMenu_Technology_00_K2Node_ComponentBoundEvent_4_OnHoveredTechnology__DelegateSignature) == 0x000008, "Wrong size on WBP_TechnologyUI_C_BndEvt__WBP_TechnologyUI_WBP_MainMenu_Technology_00_K2Node_ComponentBoundEvent_4_OnHoveredTechnology__DelegateSignature");
static_assert(offsetof(WBP_TechnologyUI_C_BndEvt__WBP_TechnologyUI_WBP_MainMenu_Technology_00_K2Node_ComponentBoundEvent_4_OnHoveredTechnology__DelegateSignature, Widget) == 0x000000, "Member 'WBP_TechnologyUI_C_BndEvt__WBP_TechnologyUI_WBP_MainMenu_Technology_00_K2Node_ComponentBoundEvent_4_OnHoveredTechnology__DelegateSignature::Widget' has a wrong offset!");

// Function WBP_TechnologyUI.WBP_TechnologyUI_C.BndEvt__WBP_TechnologyUI_WBP_MainMenu_Technology_00_K2Node_ComponentBoundEvent_5_OnUnhoveredTechnology__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct WBP_TechnologyUI_C_BndEvt__WBP_TechnologyUI_WBP_MainMenu_Technology_00_K2Node_ComponentBoundEvent_5_OnUnhoveredTechnology__DelegateSignature final
{
public:
	class UWBP_MainMenu_Technology_Content_C*     Widget;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_TechnologyUI_C_BndEvt__WBP_TechnologyUI_WBP_MainMenu_Technology_00_K2Node_ComponentBoundEvent_5_OnUnhoveredTechnology__DelegateSignature) == 0x000008, "Wrong alignment on WBP_TechnologyUI_C_BndEvt__WBP_TechnologyUI_WBP_MainMenu_Technology_00_K2Node_ComponentBoundEvent_5_OnUnhoveredTechnology__DelegateSignature");
static_assert(sizeof(WBP_TechnologyUI_C_BndEvt__WBP_TechnologyUI_WBP_MainMenu_Technology_00_K2Node_ComponentBoundEvent_5_OnUnhoveredTechnology__DelegateSignature) == 0x000008, "Wrong size on WBP_TechnologyUI_C_BndEvt__WBP_TechnologyUI_WBP_MainMenu_Technology_00_K2Node_ComponentBoundEvent_5_OnUnhoveredTechnology__DelegateSignature");
static_assert(offsetof(WBP_TechnologyUI_C_BndEvt__WBP_TechnologyUI_WBP_MainMenu_Technology_00_K2Node_ComponentBoundEvent_5_OnUnhoveredTechnology__DelegateSignature, Widget) == 0x000000, "Member 'WBP_TechnologyUI_C_BndEvt__WBP_TechnologyUI_WBP_MainMenu_Technology_00_K2Node_ComponentBoundEvent_5_OnUnhoveredTechnology__DelegateSignature::Widget' has a wrong offset!");

// Function WBP_TechnologyUI.WBP_TechnologyUI_C.ExecuteUbergraph_WBP_TechnologyUI
// 0x0090 (0x0090 - 0x0000)
struct WBP_TechnologyUI_C_ExecuteUbergraph_WBP_TechnologyUI final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0004(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_58FE[0x4];                                     // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGeometry                              K2Node_Event_MyGeometry;                           // 0x0018(0x0040)(IsPlainOldData, NoDestructor)
	float                                         K2Node_Event_InDeltaTime;                          // 0x0058(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_58FF[0x4];                                     // 0x005C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_MainMenu_Technology_Content_C*     K2Node_ComponentBoundEvent_Widget_2;               // 0x0060(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0068(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5900[0x7];                                     // 0x0069(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_MainMenu_Technology_Content_C*     K2Node_ComponentBoundEvent_Widget_1;               // 0x0070(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UWBP_MainMenu_Technology_Content_C*     K2Node_ComponentBoundEvent_Widget;                 // 0x0078(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UPalTechnologyData*                     CallFunc_GetLocalTechnologyData_ReturnValue;       // 0x0080(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0088(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_2;                    // 0x0089(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_TechnologyUI_C_ExecuteUbergraph_WBP_TechnologyUI) == 0x000008, "Wrong alignment on WBP_TechnologyUI_C_ExecuteUbergraph_WBP_TechnologyUI");
static_assert(sizeof(WBP_TechnologyUI_C_ExecuteUbergraph_WBP_TechnologyUI) == 0x000090, "Wrong size on WBP_TechnologyUI_C_ExecuteUbergraph_WBP_TechnologyUI");
static_assert(offsetof(WBP_TechnologyUI_C_ExecuteUbergraph_WBP_TechnologyUI, EntryPoint) == 0x000000, "Member 'WBP_TechnologyUI_C_ExecuteUbergraph_WBP_TechnologyUI::EntryPoint' has a wrong offset!");
static_assert(offsetof(WBP_TechnologyUI_C_ExecuteUbergraph_WBP_TechnologyUI, K2Node_CreateDelegate_OutputDelegate) == 0x000004, "Member 'WBP_TechnologyUI_C_ExecuteUbergraph_WBP_TechnologyUI::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(WBP_TechnologyUI_C_ExecuteUbergraph_WBP_TechnologyUI, K2Node_Event_MyGeometry) == 0x000018, "Member 'WBP_TechnologyUI_C_ExecuteUbergraph_WBP_TechnologyUI::K2Node_Event_MyGeometry' has a wrong offset!");
static_assert(offsetof(WBP_TechnologyUI_C_ExecuteUbergraph_WBP_TechnologyUI, K2Node_Event_InDeltaTime) == 0x000058, "Member 'WBP_TechnologyUI_C_ExecuteUbergraph_WBP_TechnologyUI::K2Node_Event_InDeltaTime' has a wrong offset!");
static_assert(offsetof(WBP_TechnologyUI_C_ExecuteUbergraph_WBP_TechnologyUI, K2Node_ComponentBoundEvent_Widget_2) == 0x000060, "Member 'WBP_TechnologyUI_C_ExecuteUbergraph_WBP_TechnologyUI::K2Node_ComponentBoundEvent_Widget_2' has a wrong offset!");
static_assert(offsetof(WBP_TechnologyUI_C_ExecuteUbergraph_WBP_TechnologyUI, CallFunc_IsValid_ReturnValue) == 0x000068, "Member 'WBP_TechnologyUI_C_ExecuteUbergraph_WBP_TechnologyUI::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TechnologyUI_C_ExecuteUbergraph_WBP_TechnologyUI, K2Node_ComponentBoundEvent_Widget_1) == 0x000070, "Member 'WBP_TechnologyUI_C_ExecuteUbergraph_WBP_TechnologyUI::K2Node_ComponentBoundEvent_Widget_1' has a wrong offset!");
static_assert(offsetof(WBP_TechnologyUI_C_ExecuteUbergraph_WBP_TechnologyUI, K2Node_ComponentBoundEvent_Widget) == 0x000078, "Member 'WBP_TechnologyUI_C_ExecuteUbergraph_WBP_TechnologyUI::K2Node_ComponentBoundEvent_Widget' has a wrong offset!");
static_assert(offsetof(WBP_TechnologyUI_C_ExecuteUbergraph_WBP_TechnologyUI, CallFunc_GetLocalTechnologyData_ReturnValue) == 0x000080, "Member 'WBP_TechnologyUI_C_ExecuteUbergraph_WBP_TechnologyUI::CallFunc_GetLocalTechnologyData_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TechnologyUI_C_ExecuteUbergraph_WBP_TechnologyUI, CallFunc_IsValid_ReturnValue_1) == 0x000088, "Member 'WBP_TechnologyUI_C_ExecuteUbergraph_WBP_TechnologyUI::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_TechnologyUI_C_ExecuteUbergraph_WBP_TechnologyUI, CallFunc_IsValid_ReturnValue_2) == 0x000089, "Member 'WBP_TechnologyUI_C_ExecuteUbergraph_WBP_TechnologyUI::CallFunc_IsValid_ReturnValue_2' has a wrong offset!");

// Function WBP_TechnologyUI.WBP_TechnologyUI_C.On Close Dialog
// 0x0018 (0x0018 - 0x0000)
struct WBP_TechnologyUI_C_On_Close_Dialog final
{
public:
	bool                                          bResult;                                           // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5901[0x6];                                     // 0x0002(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UPalTechnologyData*                     CallFunc_GetLocalTechnologyData_ReturnValue;       // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class FName                                   CallFunc_GetBindedTechnologyName_technologyName;   // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_TechnologyUI_C_On_Close_Dialog) == 0x000008, "Wrong alignment on WBP_TechnologyUI_C_On_Close_Dialog");
static_assert(sizeof(WBP_TechnologyUI_C_On_Close_Dialog) == 0x000018, "Wrong size on WBP_TechnologyUI_C_On_Close_Dialog");
static_assert(offsetof(WBP_TechnologyUI_C_On_Close_Dialog, bResult) == 0x000000, "Member 'WBP_TechnologyUI_C_On_Close_Dialog::bResult' has a wrong offset!");
static_assert(offsetof(WBP_TechnologyUI_C_On_Close_Dialog, CallFunc_IsValid_ReturnValue) == 0x000001, "Member 'WBP_TechnologyUI_C_On_Close_Dialog::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TechnologyUI_C_On_Close_Dialog, CallFunc_GetLocalTechnologyData_ReturnValue) == 0x000008, "Member 'WBP_TechnologyUI_C_On_Close_Dialog::CallFunc_GetLocalTechnologyData_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TechnologyUI_C_On_Close_Dialog, CallFunc_GetBindedTechnologyName_technologyName) == 0x000010, "Member 'WBP_TechnologyUI_C_On_Close_Dialog::CallFunc_GetBindedTechnologyName_technologyName' has a wrong offset!");

// Function WBP_TechnologyUI.WBP_TechnologyUI_C.On Unlocked Any Technology
// 0x0001 (0x0001 - 0x0000)
struct WBP_TechnologyUI_C_On_Unlocked_Any_Technology final
{
public:
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_TechnologyUI_C_On_Unlocked_Any_Technology) == 0x000001, "Wrong alignment on WBP_TechnologyUI_C_On_Unlocked_Any_Technology");
static_assert(sizeof(WBP_TechnologyUI_C_On_Unlocked_Any_Technology) == 0x000001, "Wrong size on WBP_TechnologyUI_C_On_Unlocked_Any_Technology");
static_assert(offsetof(WBP_TechnologyUI_C_On_Unlocked_Any_Technology, CallFunc_IsValid_ReturnValue) == 0x000000, "Member 'WBP_TechnologyUI_C_On_Unlocked_Any_Technology::CallFunc_IsValid_ReturnValue' has a wrong offset!");

// Function WBP_TechnologyUI.WBP_TechnologyUI_C.OnAllClearedNewFlag__DelegateSignature
// 0x0001 (0x0001 - 0x0000)
struct WBP_TechnologyUI_C_OnAllClearedNewFlag__DelegateSignature final
{
public:
	EPalUIInGameMainMenuTabType                   Tab;                                               // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_TechnologyUI_C_OnAllClearedNewFlag__DelegateSignature) == 0x000001, "Wrong alignment on WBP_TechnologyUI_C_OnAllClearedNewFlag__DelegateSignature");
static_assert(sizeof(WBP_TechnologyUI_C_OnAllClearedNewFlag__DelegateSignature) == 0x000001, "Wrong size on WBP_TechnologyUI_C_OnAllClearedNewFlag__DelegateSignature");
static_assert(offsetof(WBP_TechnologyUI_C_OnAllClearedNewFlag__DelegateSignature, Tab) == 0x000000, "Member 'WBP_TechnologyUI_C_OnAllClearedNewFlag__DelegateSignature::Tab' has a wrong offset!");

// Function WBP_TechnologyUI.WBP_TechnologyUI_C.OnClickedTechnology
// 0x0130 (0x0130 - 0x0000)
struct WBP_TechnologyUI_C_OnClickedTechnology final
{
public:
	class UWBP_MainMenu_Technology_Content_C*     Widget;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UPalTechnologyData*                     CallFunc_GetLocalTechnologyData_ReturnValue;       // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class FName                                   CallFunc_GetBindedTechnologyName_technologyName;   // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FPalTechnologyDataTableRowBase         CallFunc_GetTechlonogyBaseData_ReturnValue;        // 0x0018(0x0040)(ConstParm)
	bool                                          CallFunc_IsUnlockableRecipeTechnology_ReturnValue; // 0x0058(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5902[0x7];                                     // 0x0059(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_GetLocalizedText_ReturnValue;             // 0x0060(0x0018)()
	bool                                          CallFunc_IsUnlockRecipeTechnology_ReturnValue;     // 0x0078(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5903[0x7];                                     // 0x0079(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x0080(0x0050)(HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x00D0(0x0010)(ReferenceParm)
	TDelegate<void(bool bResult)>                 K2Node_CreateDelegate_OutputDelegate;              // 0x00E0(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class FText                                   CallFunc_GetLocalizedText_ReturnValue_1;           // 0x00F0(0x0018)()
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x0108(0x0018)()
	struct FGuid                                  CallFunc_Dialog_ReturnValue;                       // 0x0120(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_TechnologyUI_C_OnClickedTechnology) == 0x000008, "Wrong alignment on WBP_TechnologyUI_C_OnClickedTechnology");
static_assert(sizeof(WBP_TechnologyUI_C_OnClickedTechnology) == 0x000130, "Wrong size on WBP_TechnologyUI_C_OnClickedTechnology");
static_assert(offsetof(WBP_TechnologyUI_C_OnClickedTechnology, Widget) == 0x000000, "Member 'WBP_TechnologyUI_C_OnClickedTechnology::Widget' has a wrong offset!");
static_assert(offsetof(WBP_TechnologyUI_C_OnClickedTechnology, CallFunc_GetLocalTechnologyData_ReturnValue) == 0x000008, "Member 'WBP_TechnologyUI_C_OnClickedTechnology::CallFunc_GetLocalTechnologyData_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TechnologyUI_C_OnClickedTechnology, CallFunc_GetBindedTechnologyName_technologyName) == 0x000010, "Member 'WBP_TechnologyUI_C_OnClickedTechnology::CallFunc_GetBindedTechnologyName_technologyName' has a wrong offset!");
static_assert(offsetof(WBP_TechnologyUI_C_OnClickedTechnology, CallFunc_GetTechlonogyBaseData_ReturnValue) == 0x000018, "Member 'WBP_TechnologyUI_C_OnClickedTechnology::CallFunc_GetTechlonogyBaseData_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TechnologyUI_C_OnClickedTechnology, CallFunc_IsUnlockableRecipeTechnology_ReturnValue) == 0x000058, "Member 'WBP_TechnologyUI_C_OnClickedTechnology::CallFunc_IsUnlockableRecipeTechnology_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TechnologyUI_C_OnClickedTechnology, CallFunc_GetLocalizedText_ReturnValue) == 0x000060, "Member 'WBP_TechnologyUI_C_OnClickedTechnology::CallFunc_GetLocalizedText_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TechnologyUI_C_OnClickedTechnology, CallFunc_IsUnlockRecipeTechnology_ReturnValue) == 0x000078, "Member 'WBP_TechnologyUI_C_OnClickedTechnology::CallFunc_IsUnlockRecipeTechnology_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TechnologyUI_C_OnClickedTechnology, K2Node_MakeStruct_FormatArgumentData) == 0x000080, "Member 'WBP_TechnologyUI_C_OnClickedTechnology::K2Node_MakeStruct_FormatArgumentData' has a wrong offset!");
static_assert(offsetof(WBP_TechnologyUI_C_OnClickedTechnology, K2Node_MakeArray_Array) == 0x0000D0, "Member 'WBP_TechnologyUI_C_OnClickedTechnology::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(WBP_TechnologyUI_C_OnClickedTechnology, K2Node_CreateDelegate_OutputDelegate) == 0x0000E0, "Member 'WBP_TechnologyUI_C_OnClickedTechnology::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(WBP_TechnologyUI_C_OnClickedTechnology, CallFunc_GetLocalizedText_ReturnValue_1) == 0x0000F0, "Member 'WBP_TechnologyUI_C_OnClickedTechnology::CallFunc_GetLocalizedText_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_TechnologyUI_C_OnClickedTechnology, CallFunc_Format_ReturnValue) == 0x000108, "Member 'WBP_TechnologyUI_C_OnClickedTechnology::CallFunc_Format_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TechnologyUI_C_OnClickedTechnology, CallFunc_Dialog_ReturnValue) == 0x000120, "Member 'WBP_TechnologyUI_C_OnClickedTechnology::CallFunc_Dialog_ReturnValue' has a wrong offset!");

// Function WBP_TechnologyUI.WBP_TechnologyUI_C.OnHoveredTechnology
// 0x0020 (0x0020 - 0x0000)
struct WBP_TechnologyUI_C_OnHoveredTechnology final
{
public:
	class UWBP_MainMenu_Technology_Content_C*     Widget;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class FName                                   CallFunc_GetBindedTechnologyName_technologyName;   // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UTexture2D*                             K2Node_DynamicCast_AsTexture_2D;                   // 0x0010(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_TechnologyUI_C_OnHoveredTechnology) == 0x000008, "Wrong alignment on WBP_TechnologyUI_C_OnHoveredTechnology");
static_assert(sizeof(WBP_TechnologyUI_C_OnHoveredTechnology) == 0x000020, "Wrong size on WBP_TechnologyUI_C_OnHoveredTechnology");
static_assert(offsetof(WBP_TechnologyUI_C_OnHoveredTechnology, Widget) == 0x000000, "Member 'WBP_TechnologyUI_C_OnHoveredTechnology::Widget' has a wrong offset!");
static_assert(offsetof(WBP_TechnologyUI_C_OnHoveredTechnology, CallFunc_GetBindedTechnologyName_technologyName) == 0x000008, "Member 'WBP_TechnologyUI_C_OnHoveredTechnology::CallFunc_GetBindedTechnologyName_technologyName' has a wrong offset!");
static_assert(offsetof(WBP_TechnologyUI_C_OnHoveredTechnology, K2Node_DynamicCast_AsTexture_2D) == 0x000010, "Member 'WBP_TechnologyUI_C_OnHoveredTechnology::K2Node_DynamicCast_AsTexture_2D' has a wrong offset!");
static_assert(offsetof(WBP_TechnologyUI_C_OnHoveredTechnology, K2Node_DynamicCast_bSuccess) == 0x000018, "Member 'WBP_TechnologyUI_C_OnHoveredTechnology::K2Node_DynamicCast_bSuccess' has a wrong offset!");

// Function WBP_TechnologyUI.WBP_TechnologyUI_C.OnMouseMove
// 0x0310 (0x0310 - 0x0000)
struct WBP_TechnologyUI_C_OnMouseMove final
{
public:
	struct FGeometry                              MyGeometry;                                        // 0x0000(0x0040)(BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
	struct FPointerEvent                          MouseEvent;                                        // 0x0040(0x0098)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	struct FEventReply                            ReturnValue;                                       // 0x00D8(0x00B8)(Parm, OutParm, ReturnParm)
	struct FEventReply                            CallFunc_Handled_ReturnValue;                      // 0x0190(0x00B8)()
	bool                                          CallFunc_PointerEvent_IsMouseButtonDown_ReturnValue; // 0x0248(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_PointerEvent_IsMouseButtonDown_ReturnValue_1; // 0x0249(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5904[0x6];                                     // 0x024A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FEventReply                            CallFunc_Unhandled_ReturnValue;                    // 0x0250(0x00B8)()
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x0308(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_TechnologyUI_C_OnMouseMove) == 0x000008, "Wrong alignment on WBP_TechnologyUI_C_OnMouseMove");
static_assert(sizeof(WBP_TechnologyUI_C_OnMouseMove) == 0x000310, "Wrong size on WBP_TechnologyUI_C_OnMouseMove");
static_assert(offsetof(WBP_TechnologyUI_C_OnMouseMove, MyGeometry) == 0x000000, "Member 'WBP_TechnologyUI_C_OnMouseMove::MyGeometry' has a wrong offset!");
static_assert(offsetof(WBP_TechnologyUI_C_OnMouseMove, MouseEvent) == 0x000040, "Member 'WBP_TechnologyUI_C_OnMouseMove::MouseEvent' has a wrong offset!");
static_assert(offsetof(WBP_TechnologyUI_C_OnMouseMove, ReturnValue) == 0x0000D8, "Member 'WBP_TechnologyUI_C_OnMouseMove::ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TechnologyUI_C_OnMouseMove, CallFunc_Handled_ReturnValue) == 0x000190, "Member 'WBP_TechnologyUI_C_OnMouseMove::CallFunc_Handled_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TechnologyUI_C_OnMouseMove, CallFunc_PointerEvent_IsMouseButtonDown_ReturnValue) == 0x000248, "Member 'WBP_TechnologyUI_C_OnMouseMove::CallFunc_PointerEvent_IsMouseButtonDown_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TechnologyUI_C_OnMouseMove, CallFunc_PointerEvent_IsMouseButtonDown_ReturnValue_1) == 0x000249, "Member 'WBP_TechnologyUI_C_OnMouseMove::CallFunc_PointerEvent_IsMouseButtonDown_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_TechnologyUI_C_OnMouseMove, CallFunc_Unhandled_ReturnValue) == 0x000250, "Member 'WBP_TechnologyUI_C_OnMouseMove::CallFunc_Unhandled_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TechnologyUI_C_OnMouseMove, CallFunc_BooleanOR_ReturnValue) == 0x000308, "Member 'WBP_TechnologyUI_C_OnMouseMove::CallFunc_BooleanOR_ReturnValue' has a wrong offset!");

// Function WBP_TechnologyUI.WBP_TechnologyUI_C.OnUnhoveredTechnology
// 0x0020 (0x0020 - 0x0000)
struct WBP_TechnologyUI_C_OnUnhoveredTechnology final
{
public:
	class UWBP_MainMenu_Technology_Content_C*     Widget;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class FName                                   CallFunc_GetBindedTechnologyName_technologyName;   // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPalTechnologyData*                     CallFunc_GetLocalTechnologyData_ReturnValue;       // 0x0010(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsExistNewUnlockedTechnology_ReturnValue; // 0x0019(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsNewUnlockedTechnology_ReturnValue;      // 0x001A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_TechnologyUI_C_OnUnhoveredTechnology) == 0x000008, "Wrong alignment on WBP_TechnologyUI_C_OnUnhoveredTechnology");
static_assert(sizeof(WBP_TechnologyUI_C_OnUnhoveredTechnology) == 0x000020, "Wrong size on WBP_TechnologyUI_C_OnUnhoveredTechnology");
static_assert(offsetof(WBP_TechnologyUI_C_OnUnhoveredTechnology, Widget) == 0x000000, "Member 'WBP_TechnologyUI_C_OnUnhoveredTechnology::Widget' has a wrong offset!");
static_assert(offsetof(WBP_TechnologyUI_C_OnUnhoveredTechnology, CallFunc_GetBindedTechnologyName_technologyName) == 0x000008, "Member 'WBP_TechnologyUI_C_OnUnhoveredTechnology::CallFunc_GetBindedTechnologyName_technologyName' has a wrong offset!");
static_assert(offsetof(WBP_TechnologyUI_C_OnUnhoveredTechnology, CallFunc_GetLocalTechnologyData_ReturnValue) == 0x000010, "Member 'WBP_TechnologyUI_C_OnUnhoveredTechnology::CallFunc_GetLocalTechnologyData_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TechnologyUI_C_OnUnhoveredTechnology, CallFunc_IsValid_ReturnValue) == 0x000018, "Member 'WBP_TechnologyUI_C_OnUnhoveredTechnology::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TechnologyUI_C_OnUnhoveredTechnology, CallFunc_IsExistNewUnlockedTechnology_ReturnValue) == 0x000019, "Member 'WBP_TechnologyUI_C_OnUnhoveredTechnology::CallFunc_IsExistNewUnlockedTechnology_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TechnologyUI_C_OnUnhoveredTechnology, CallFunc_IsNewUnlockedTechnology_ReturnValue) == 0x00001A, "Member 'WBP_TechnologyUI_C_OnUnhoveredTechnology::CallFunc_IsNewUnlockedTechnology_ReturnValue' has a wrong offset!");

// Function WBP_TechnologyUI.WBP_TechnologyUI_C.Setup
// 0x0010 (0x0010 - 0x0000)
struct WBP_TechnologyUI_C_Setup final
{
public:
	class UWidget*                                CallFunc_GetTopUnlockableFocusTarget_Target;       // 0x0000(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_TechnologyUI_C_Setup) == 0x000008, "Wrong alignment on WBP_TechnologyUI_C_Setup");
static_assert(sizeof(WBP_TechnologyUI_C_Setup) == 0x000010, "Wrong size on WBP_TechnologyUI_C_Setup");
static_assert(offsetof(WBP_TechnologyUI_C_Setup, CallFunc_GetTopUnlockableFocusTarget_Target) == 0x000000, "Member 'WBP_TechnologyUI_C_Setup::CallFunc_GetTopUnlockableFocusTarget_Target' has a wrong offset!");
static_assert(offsetof(WBP_TechnologyUI_C_Setup, CallFunc_IsValid_ReturnValue) == 0x000008, "Member 'WBP_TechnologyUI_C_Setup::CallFunc_IsValid_ReturnValue' has a wrong offset!");

// Function WBP_TechnologyUI.WBP_TechnologyUI_C.Tick
// 0x0048 (0x0048 - 0x0000)
struct WBP_TechnologyUI_C_Tick final
{
public:
	struct FGeometry                              MyGeometry;                                        // 0x0000(0x0040)(BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
	float                                         InDeltaTime;                                       // 0x0040(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_TechnologyUI_C_Tick) == 0x000008, "Wrong alignment on WBP_TechnologyUI_C_Tick");
static_assert(sizeof(WBP_TechnologyUI_C_Tick) == 0x000048, "Wrong size on WBP_TechnologyUI_C_Tick");
static_assert(offsetof(WBP_TechnologyUI_C_Tick, MyGeometry) == 0x000000, "Member 'WBP_TechnologyUI_C_Tick::MyGeometry' has a wrong offset!");
static_assert(offsetof(WBP_TechnologyUI_C_Tick, InDeltaTime) == 0x000040, "Member 'WBP_TechnologyUI_C_Tick::InDeltaTime' has a wrong offset!");

// Function WBP_TechnologyUI.WBP_TechnologyUI_C.BP_GetDesiredFocusTarget
// 0x0018 (0x0018 - 0x0000)
struct WBP_TechnologyUI_C_BP_GetDesiredFocusTarget final
{
public:
	class UWidget*                                ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5905[0x7];                                     // 0x0009(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidget*                                CallFunc_GetTopFocusTarget_Target;                 // 0x0010(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_TechnologyUI_C_BP_GetDesiredFocusTarget) == 0x000008, "Wrong alignment on WBP_TechnologyUI_C_BP_GetDesiredFocusTarget");
static_assert(sizeof(WBP_TechnologyUI_C_BP_GetDesiredFocusTarget) == 0x000018, "Wrong size on WBP_TechnologyUI_C_BP_GetDesiredFocusTarget");
static_assert(offsetof(WBP_TechnologyUI_C_BP_GetDesiredFocusTarget, ReturnValue) == 0x000000, "Member 'WBP_TechnologyUI_C_BP_GetDesiredFocusTarget::ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TechnologyUI_C_BP_GetDesiredFocusTarget, CallFunc_IsValid_ReturnValue) == 0x000008, "Member 'WBP_TechnologyUI_C_BP_GetDesiredFocusTarget::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TechnologyUI_C_BP_GetDesiredFocusTarget, CallFunc_GetTopFocusTarget_Target) == 0x000010, "Member 'WBP_TechnologyUI_C_BP_GetDesiredFocusTarget::CallFunc_GetTopFocusTarget_Target' has a wrong offset!");

}

