#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_PalStatus

#include "Basic.hpp"

#include "WBP_PalStatus_classes.hpp"
#include "WBP_PalStatus_parameters.hpp"


namespace SDK
{

// Function WBP_PalStatus.WBP_PalStatus_C.BackToList
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_PalStatus_C::BackToList()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PalStatus_C", "BackToList");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_PalStatus.WBP_PalStatus_C.BndEvt__WBP_PalStatus_WBP_MainMenu_Pal_00_K2Node_ComponentBoundEvent_0_OnClickedAnyPalPanel__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UPalIndividualCharacterHandle*    Handle                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_PalStatus_C::BndEvt__WBP_PalStatus_WBP_MainMenu_Pal_00_K2Node_ComponentBoundEvent_0_OnClickedAnyPalPanel__DelegateSignature(class UPalIndividualCharacterHandle* Handle)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PalStatus_C", "BndEvt__WBP_PalStatus_WBP_MainMenu_Pal_00_K2Node_ComponentBoundEvent_0_OnClickedAnyPalPanel__DelegateSignature");

	Params::WBP_PalStatus_C_BndEvt__WBP_PalStatus_WBP_MainMenu_Pal_00_K2Node_ComponentBoundEvent_0_OnClickedAnyPalPanel__DelegateSignature Parms{};

	Parms.Handle = Handle;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_PalStatus.WBP_PalStatus_C.BndEvt__WBP_PalStatus_WBP_MainMenu_Pal_00_K2Node_ComponentBoundEvent_1_OnHoveredAnyPalPanel__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UPalIndividualCharacterHandle*    Handle                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_PalStatus_C::BndEvt__WBP_PalStatus_WBP_MainMenu_Pal_00_K2Node_ComponentBoundEvent_1_OnHoveredAnyPalPanel__DelegateSignature(class UPalIndividualCharacterHandle* Handle)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PalStatus_C", "BndEvt__WBP_PalStatus_WBP_MainMenu_Pal_00_K2Node_ComponentBoundEvent_1_OnHoveredAnyPalPanel__DelegateSignature");

	Params::WBP_PalStatus_C_BndEvt__WBP_PalStatus_WBP_MainMenu_Pal_00_K2Node_ComponentBoundEvent_1_OnHoveredAnyPalPanel__DelegateSignature Parms{};

	Parms.Handle = Handle;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_PalStatus.WBP_PalStatus_C.BndEvt__WBP_PalStatus_WBP_MainMenu_Pal_00_K2Node_ComponentBoundEvent_2_OnUnhoveredAnyPalPanel__DelegateSignature
// (BlueprintEvent)

void UWBP_PalStatus_C::BndEvt__WBP_PalStatus_WBP_MainMenu_Pal_00_K2Node_ComponentBoundEvent_2_OnUnhoveredAnyPalPanel__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PalStatus_C", "BndEvt__WBP_PalStatus_WBP_MainMenu_Pal_00_K2Node_ComponentBoundEvent_2_OnUnhoveredAnyPalPanel__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_PalStatus.WBP_PalStatus_C.BndEvt__WBP_PalStatus_WBP_MainMenu_Pal_00_K2Node_ComponentBoundEvent_3_OnCommitedNickName__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class FText                             NewNickName                                            (BlueprintVisible, BlueprintReadOnly, Parm)

void UWBP_PalStatus_C::BndEvt__WBP_PalStatus_WBP_MainMenu_Pal_00_K2Node_ComponentBoundEvent_3_OnCommitedNickName__DelegateSignature(const class FText& NewNickName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PalStatus_C", "BndEvt__WBP_PalStatus_WBP_MainMenu_Pal_00_K2Node_ComponentBoundEvent_3_OnCommitedNickName__DelegateSignature");

	Params::WBP_PalStatus_C_BndEvt__WBP_PalStatus_WBP_MainMenu_Pal_00_K2Node_ComponentBoundEvent_3_OnCommitedNickName__DelegateSignature Parms{};

	Parms.NewNickName = std::move(NewNickName);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_PalStatus.WBP_PalStatus_C.BndEvt__WBP_PalStatus_WBP_MainMenu_Pal_00_K2Node_ComponentBoundEvent_4_OnRequestedRemoveWaza__DelegateSignature
// (BlueprintEvent)
// Parameters:
// EPalWazaID                              WazaID                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UPalIndividualCharacterHandle*    TargetHandle                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_PalStatus_C::BndEvt__WBP_PalStatus_WBP_MainMenu_Pal_00_K2Node_ComponentBoundEvent_4_OnRequestedRemoveWaza__DelegateSignature(EPalWazaID WazaID, class UPalIndividualCharacterHandle* TargetHandle)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PalStatus_C", "BndEvt__WBP_PalStatus_WBP_MainMenu_Pal_00_K2Node_ComponentBoundEvent_4_OnRequestedRemoveWaza__DelegateSignature");

	Params::WBP_PalStatus_C_BndEvt__WBP_PalStatus_WBP_MainMenu_Pal_00_K2Node_ComponentBoundEvent_4_OnRequestedRemoveWaza__DelegateSignature Parms{};

	Parms.WazaID = WazaID;
	Parms.TargetHandle = TargetHandle;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_PalStatus.WBP_PalStatus_C.BndEvt__WBP_PalStatus_WBP_MainMenu_Pal_00_K2Node_ComponentBoundEvent_5_OnSelectedChangeActiveSkill__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UPalIndividualCharacterHandle*    TargetHandle                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// EPalWazaID                              ChangeWazaID                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EPalWazaID                              NewWazaID                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_PalStatus_C::BndEvt__WBP_PalStatus_WBP_MainMenu_Pal_00_K2Node_ComponentBoundEvent_5_OnSelectedChangeActiveSkill__DelegateSignature(class UPalIndividualCharacterHandle* TargetHandle, EPalWazaID ChangeWazaID, EPalWazaID NewWazaID)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PalStatus_C", "BndEvt__WBP_PalStatus_WBP_MainMenu_Pal_00_K2Node_ComponentBoundEvent_5_OnSelectedChangeActiveSkill__DelegateSignature");

	Params::WBP_PalStatus_C_BndEvt__WBP_PalStatus_WBP_MainMenu_Pal_00_K2Node_ComponentBoundEvent_5_OnSelectedChangeActiveSkill__DelegateSignature Parms{};

	Parms.TargetHandle = TargetHandle;
	Parms.ChangeWazaID = ChangeWazaID;
	Parms.NewWazaID = NewWazaID;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_PalStatus.WBP_PalStatus_C.ClampInputNickName
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FText                             InText                                                 (BlueprintVisible, BlueprintReadOnly, Parm)
// class FText                             ClampedNickName                                        (Parm, OutParm)

void UWBP_PalStatus_C::ClampInputNickName(const class FText& InText, class FText* ClampedNickName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PalStatus_C", "ClampInputNickName");

	Params::WBP_PalStatus_C_ClampInputNickName Parms{};

	Parms.InText = std::move(InText);

	UObject::ProcessEvent(Func, &Parms);

	if (ClampedNickName != nullptr)
		*ClampedNickName = std::move(Parms.ClampedNickName);
}


// Function WBP_PalStatus.WBP_PalStatus_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_PalStatus_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PalStatus_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_PalStatus.WBP_PalStatus_C.Destruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_PalStatus_C::Destruct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PalStatus_C", "Destruct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_PalStatus.WBP_PalStatus_C.ExecuteUbergraph_WBP_PalStatus
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_PalStatus_C::ExecuteUbergraph_WBP_PalStatus(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PalStatus_C", "ExecuteUbergraph_WBP_PalStatus");

	Params::WBP_PalStatus_C_ExecuteUbergraph_WBP_PalStatus Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_PalStatus.WBP_PalStatus_C.Get Panel Index from Handle
// (Private, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class UPalIndividualCharacterHandle*    Handle                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// int32                                   Param_Index                                            (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    IsValid                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_PalStatus_C::Get_Panel_Index_from_Handle(class UPalIndividualCharacterHandle* Handle, int32* Param_Index, bool* IsValid)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PalStatus_C", "Get Panel Index from Handle");

	Params::WBP_PalStatus_C_Get_Panel_Index_from_Handle Parms{};

	Parms.Handle = Handle;

	UObject::ProcessEvent(Func, &Parms);

	if (Param_Index != nullptr)
		*Param_Index = Parms.Param_Index;

	if (IsValid != nullptr)
		*IsValid = Parms.IsValid;
}


// Function WBP_PalStatus.WBP_PalStatus_C.HoveredAnyPalPanel_Internal
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UPalIndividualCharacterHandle*    Handle                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_PalStatus_C::HoveredAnyPalPanel_Internal(class UPalIndividualCharacterHandle* Handle)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PalStatus_C", "HoveredAnyPalPanel_Internal");

	Params::WBP_PalStatus_C_HoveredAnyPalPanel_Internal Parms{};

	Parms.Handle = Handle;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_PalStatus.WBP_PalStatus_C.Is Editing Nick Name
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool                                    IsEditing                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_PalStatus_C::Is_Editing_Nick_Name(bool* IsEditing)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PalStatus_C", "Is Editing Nick Name");

	Params::WBP_PalStatus_C_Is_Editing_Nick_Name Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (IsEditing != nullptr)
		*IsEditing = Parms.IsEditing;
}


// Function WBP_PalStatus.WBP_PalStatus_C.NickNameFinalCheck
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FText                             InText                                                 (BlueprintVisible, BlueprintReadOnly, Parm)
// ETextCommit                             TextCommit                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FText                             FinalNickName                                          (Parm, OutParm)

void UWBP_PalStatus_C::NickNameFinalCheck(const class FText& InText, ETextCommit TextCommit, class FText* FinalNickName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PalStatus_C", "NickNameFinalCheck");

	Params::WBP_PalStatus_C_NickNameFinalCheck Parms{};

	Parms.InText = std::move(InText);
	Parms.TextCommit = TextCommit;

	UObject::ProcessEvent(Func, &Parms);

	if (FinalNickName != nullptr)
		*FinalNickName = std::move(Parms.FinalNickName);
}


// Function WBP_PalStatus.WBP_PalStatus_C.OnClosedDropPalDialog
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bResult                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_PalStatus_C::OnClosedDropPalDialog(bool bResult)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PalStatus_C", "OnClosedDropPalDialog");

	Params::WBP_PalStatus_C_OnClosedDropPalDialog Parms{};

	Parms.bResult = bResult;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_PalStatus.WBP_PalStatus_C.OnCompletedCaptureActorSetup
// (BlueprintCallable, BlueprintEvent)

void UWBP_PalStatus_C::OnCompletedCaptureActorSetup()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PalStatus_C", "OnCompletedCaptureActorSetup");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_PalStatus.WBP_PalStatus_C.OnTriggerDropPal
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWBP_PalStatus_C::OnTriggerDropPal()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PalStatus_C", "OnTriggerDropPal");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_PalStatus.WBP_PalStatus_C.Setup
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<class UPalIndividualCharacterHandle*>Handles                                                (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UWBP_PalStatus_C::Setup(TArray<class UPalIndividualCharacterHandle*>& Handles)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PalStatus_C", "Setup");

	Params::WBP_PalStatus_C_Setup Parms{};

	Parms.Handles = std::move(Handles);

	UObject::ProcessEvent(Func, &Parms);

	Handles = std::move(Parms.Handles);
}


// Function WBP_PalStatus.WBP_PalStatus_C.Setup One Pal
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UPalIndividualCharacterHandle*    CharacterHandle                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_PalStatus_C::Setup_One_Pal(class UPalIndividualCharacterHandle* CharacterHandle)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PalStatus_C", "Setup One Pal");

	Params::WBP_PalStatus_C_Setup_One_Pal Parms{};

	Parms.CharacterHandle = CharacterHandle;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_PalStatus.WBP_PalStatus_C.Setup_MultiPal
// (Private, BlueprintCallable, BlueprintEvent)

void UWBP_PalStatus_C::Setup_MultiPal()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PalStatus_C", "Setup_MultiPal");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_PalStatus.WBP_PalStatus_C.Setup_NothingPal
// (Private, BlueprintCallable, BlueprintEvent)

void UWBP_PalStatus_C::Setup_NothingPal()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PalStatus_C", "Setup_NothingPal");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_PalStatus.WBP_PalStatus_C.SetupInputAction
// (Private, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWBP_PalStatus_C::SetupInputAction()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PalStatus_C", "SetupInputAction");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_PalStatus.WBP_PalStatus_C.ShouldBackList
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool                                    ShouldBack                                             (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_PalStatus_C::ShouldBackList(bool* ShouldBack)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PalStatus_C", "ShouldBackList");

	Params::WBP_PalStatus_C_ShouldBackList Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (ShouldBack != nullptr)
		*ShouldBack = Parms.ShouldBack;
}


// Function WBP_PalStatus.WBP_PalStatus_C.ToParameterDetail
// (Private, BlueprintCallable, BlueprintEvent)

void UWBP_PalStatus_C::ToParameterDetail()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PalStatus_C", "ToParameterDetail");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_PalStatus.WBP_PalStatus_C.ToSkillDetail
// (Private, BlueprintCallable, BlueprintEvent)

void UWBP_PalStatus_C::ToSkillDetail()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PalStatus_C", "ToSkillDetail");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_PalStatus.WBP_PalStatus_C.UnbindInputAction
// (Private, BlueprintCallable, BlueprintEvent)

void UWBP_PalStatus_C::UnbindInputAction()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PalStatus_C", "UnbindInputAction");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_PalStatus.WBP_PalStatus_C.UnhoveredAnyPalPanel_Internal
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_PalStatus_C::UnhoveredAnyPalPanel_Internal()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PalStatus_C", "UnhoveredAnyPalPanel_Internal");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_PalStatus.WBP_PalStatus_C.BP_GetDesiredFocusTarget
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)

class UWidget* UWBP_PalStatus_C::BP_GetDesiredFocusTarget() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PalStatus_C", "BP_GetDesiredFocusTarget");

	Params::WBP_PalStatus_C_BP_GetDesiredFocusTarget Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

