#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Ingameconstruction_KeyGuide

#include "Basic.hpp"

#include "WBP_Ingameconstruction_KeyGuide_classes.hpp"
#include "WBP_Ingameconstruction_KeyGuide_parameters.hpp"


namespace SDK
{

// Function WBP_Ingameconstruction_KeyGuide.WBP_Ingameconstruction_KeyGuide_C.Setup
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<class FName>                     ActionNames                                            (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// class FText                             DisplayText                                            (BlueprintVisible, BlueprintReadOnly, Parm)

void UWBP_Ingameconstruction_KeyGuide_C::Setup(TArray<class FName>& ActionNames, const class FText& DisplayText)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Ingameconstruction_KeyGuide_C", "Setup");

	Params::WBP_Ingameconstruction_KeyGuide_C_Setup Parms{};

	Parms.ActionNames = std::move(ActionNames);
	Parms.DisplayText = std::move(DisplayText);

	UObject::ProcessEvent(Func, &Parms);

	ActionNames = std::move(Parms.ActionNames);
}

}

